// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: an-gpon-pm-olt-transceivers.proto

package com.telemetry;

public final class AnGponPmOltTransceivers {
  private AnGponPmOltTransceivers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GponOltTransceiversOrBuilder extends
      // @@protoc_insertion_point(interface_extends:an_gpon_olt_transceivers.GponOltTransceivers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    java.util.List<com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver> 
        getGponOltTransceiverList();
    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver getGponOltTransceiver(int index);
    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    int getGponOltTransceiverCount();
    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    java.util.List<? extends com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder> 
        getGponOltTransceiverOrBuilderList();
    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder getGponOltTransceiverOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code an_gpon_olt_transceivers.GponOltTransceivers}
   */
  public  static final class GponOltTransceivers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:an_gpon_olt_transceivers.GponOltTransceivers)
      GponOltTransceiversOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GponOltTransceivers.newBuilder() to construct.
    private GponOltTransceivers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GponOltTransceivers() {
      gponOltTransceiver_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GponOltTransceivers();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GponOltTransceivers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                gponOltTransceiver_ = new java.util.ArrayList<com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver>();
                mutable_bitField0_ |= 0x00000001;
              }
              gponOltTransceiver_.add(
                  input.readMessage(com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          gponOltTransceiver_ = java.util.Collections.unmodifiableList(gponOltTransceiver_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.class, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.Builder.class);
    }

    public interface GponOltTransceiverOrBuilder extends
        // @@protoc_insertion_point(interface_extends:an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *端口ID名称，格式：Gpon.f.s.p
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      java.lang.String getName();
      /**
       * <pre>
       *端口ID名称，格式：Gpon.f.s.p
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <pre>
       *光模块温度，单位0.01℃
       * </pre>
       *
       * <code>int32 temperature = 2;</code>
       * @return The temperature.
       */
      int getTemperature();

      /**
       * <pre>
       *光模块供电电压， 单位0.01V
       * </pre>
       *
       * <code>int32 supply_voltage = 3;</code>
       * @return The supplyVoltage.
       */
      int getSupplyVoltage();

      /**
       * <pre>
       *通道1类型
       * </pre>
       *
       * <code>int32 channel_1_type = 4;</code>
       * @return The channel1Type.
       */
      int getChannel1Type();

      /**
       * <pre>
       *通道1发送偏置电流，单位0.01mA
       * </pre>
       *
       * <code>int32 channel_1_tx_bias = 5;</code>
       * @return The channel1TxBias.
       */
      int getChannel1TxBias();

      /**
       * <pre>
       *通道1发送功率，单位0.01dBm，
       * </pre>
       *
       * <code>int32 channel_1_tx_power = 6;</code>
       * @return The channel1TxPower.
       */
      int getChannel1TxPower();

      /**
       * <pre>
       *通道1空闲时刻的接收光功率，单位0.01dBm 【未连接 onu 时， pon口 接收光功率为 -40db】
       * </pre>
       *
       * <code>int32 channel_1_idle_rssi = 7;</code>
       * @return The channel1IdleRssi.
       */
      int getChannel1IdleRssi();

      /**
       * <pre>
       *通道2类型 【0x01 : GBIC ; 0x02 : SFF ; 0x03 : SFP】
       * </pre>
       *
       * <code>int32 channel_2_type = 8;</code>
       * @return The channel2Type.
       */
      int getChannel2Type();

      /**
       * <pre>
       *通道2发送偏置电流，单位0.01mA
       * </pre>
       *
       * <code>int32 channel_2_tx_bias = 9;</code>
       * @return The channel2TxBias.
       */
      int getChannel2TxBias();

      /**
       * <pre>
       *通道2发送功率，单位0.01dBm
       * </pre>
       *
       * <code>int32 channel_2_tx_power = 10;</code>
       * @return The channel2TxPower.
       */
      int getChannel2TxPower();

      /**
       * <pre>
       *通道2空闲时刻的接收光功率，单位0.01dBm
       * </pre>
       *
       * <code>int32 channel_2_idle_rssi = 11;</code>
       * @return The channel2IdleRssi.
       */
      int getChannel2IdleRssi();

      /**
       * <pre>
       *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
       * </pre>
       *
       * <code>int32 module_type = 12;</code>
       * @return The moduleType.
       */
      int getModuleType();

      /**
       * <pre>
       *【 类似 N2&amp;C+，N1&amp;B+。。。。光模块类型 】
       * </pre>
       *
       * <code>string module_sub_type = 13;</code>
       * @return The moduleSubType.
       */
      java.lang.String getModuleSubType();
      /**
       * <pre>
       *【 类似 N2&amp;C+，N1&amp;B+。。。。光模块类型 】
       * </pre>
       *
       * <code>string module_sub_type = 13;</code>
       * @return The bytes for moduleSubType.
       */
      com.google.protobuf.ByteString
          getModuleSubTypeBytes();
    }
    /**
     * Protobuf type {@code an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver}
     */
    public  static final class GponOltTransceiver extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver)
        GponOltTransceiverOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use GponOltTransceiver.newBuilder() to construct.
      private GponOltTransceiver(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private GponOltTransceiver() {
        name_ = "";
        moduleSubType_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new GponOltTransceiver();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private GponOltTransceiver(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 16: {

                temperature_ = input.readInt32();
                break;
              }
              case 24: {

                supplyVoltage_ = input.readInt32();
                break;
              }
              case 32: {

                channel1Type_ = input.readInt32();
                break;
              }
              case 40: {

                channel1TxBias_ = input.readInt32();
                break;
              }
              case 48: {

                channel1TxPower_ = input.readInt32();
                break;
              }
              case 56: {

                channel1IdleRssi_ = input.readInt32();
                break;
              }
              case 64: {

                channel2Type_ = input.readInt32();
                break;
              }
              case 72: {

                channel2TxBias_ = input.readInt32();
                break;
              }
              case 80: {

                channel2TxPower_ = input.readInt32();
                break;
              }
              case 88: {

                channel2IdleRssi_ = input.readInt32();
                break;
              }
              case 96: {

                moduleType_ = input.readInt32();
                break;
              }
              case 106: {
                java.lang.String s = input.readStringRequireUtf8();

                moduleSubType_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.class, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <pre>
       *端口ID名称，格式：Gpon.f.s.p
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *端口ID名称，格式：Gpon.f.s.p
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TEMPERATURE_FIELD_NUMBER = 2;
      private int temperature_;
      /**
       * <pre>
       *光模块温度，单位0.01℃
       * </pre>
       *
       * <code>int32 temperature = 2;</code>
       * @return The temperature.
       */
      public int getTemperature() {
        return temperature_;
      }

      public static final int SUPPLY_VOLTAGE_FIELD_NUMBER = 3;
      private int supplyVoltage_;
      /**
       * <pre>
       *光模块供电电压， 单位0.01V
       * </pre>
       *
       * <code>int32 supply_voltage = 3;</code>
       * @return The supplyVoltage.
       */
      public int getSupplyVoltage() {
        return supplyVoltage_;
      }

      public static final int CHANNEL_1_TYPE_FIELD_NUMBER = 4;
      private int channel1Type_;
      /**
       * <pre>
       *通道1类型
       * </pre>
       *
       * <code>int32 channel_1_type = 4;</code>
       * @return The channel1Type.
       */
      public int getChannel1Type() {
        return channel1Type_;
      }

      public static final int CHANNEL_1_TX_BIAS_FIELD_NUMBER = 5;
      private int channel1TxBias_;
      /**
       * <pre>
       *通道1发送偏置电流，单位0.01mA
       * </pre>
       *
       * <code>int32 channel_1_tx_bias = 5;</code>
       * @return The channel1TxBias.
       */
      public int getChannel1TxBias() {
        return channel1TxBias_;
      }

      public static final int CHANNEL_1_TX_POWER_FIELD_NUMBER = 6;
      private int channel1TxPower_;
      /**
       * <pre>
       *通道1发送功率，单位0.01dBm，
       * </pre>
       *
       * <code>int32 channel_1_tx_power = 6;</code>
       * @return The channel1TxPower.
       */
      public int getChannel1TxPower() {
        return channel1TxPower_;
      }

      public static final int CHANNEL_1_IDLE_RSSI_FIELD_NUMBER = 7;
      private int channel1IdleRssi_;
      /**
       * <pre>
       *通道1空闲时刻的接收光功率，单位0.01dBm 【未连接 onu 时， pon口 接收光功率为 -40db】
       * </pre>
       *
       * <code>int32 channel_1_idle_rssi = 7;</code>
       * @return The channel1IdleRssi.
       */
      public int getChannel1IdleRssi() {
        return channel1IdleRssi_;
      }

      public static final int CHANNEL_2_TYPE_FIELD_NUMBER = 8;
      private int channel2Type_;
      /**
       * <pre>
       *通道2类型 【0x01 : GBIC ; 0x02 : SFF ; 0x03 : SFP】
       * </pre>
       *
       * <code>int32 channel_2_type = 8;</code>
       * @return The channel2Type.
       */
      public int getChannel2Type() {
        return channel2Type_;
      }

      public static final int CHANNEL_2_TX_BIAS_FIELD_NUMBER = 9;
      private int channel2TxBias_;
      /**
       * <pre>
       *通道2发送偏置电流，单位0.01mA
       * </pre>
       *
       * <code>int32 channel_2_tx_bias = 9;</code>
       * @return The channel2TxBias.
       */
      public int getChannel2TxBias() {
        return channel2TxBias_;
      }

      public static final int CHANNEL_2_TX_POWER_FIELD_NUMBER = 10;
      private int channel2TxPower_;
      /**
       * <pre>
       *通道2发送功率，单位0.01dBm
       * </pre>
       *
       * <code>int32 channel_2_tx_power = 10;</code>
       * @return The channel2TxPower.
       */
      public int getChannel2TxPower() {
        return channel2TxPower_;
      }

      public static final int CHANNEL_2_IDLE_RSSI_FIELD_NUMBER = 11;
      private int channel2IdleRssi_;
      /**
       * <pre>
       *通道2空闲时刻的接收光功率，单位0.01dBm
       * </pre>
       *
       * <code>int32 channel_2_idle_rssi = 11;</code>
       * @return The channel2IdleRssi.
       */
      public int getChannel2IdleRssi() {
        return channel2IdleRssi_;
      }

      public static final int MODULE_TYPE_FIELD_NUMBER = 12;
      private int moduleType_;
      /**
       * <pre>
       *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
       * </pre>
       *
       * <code>int32 module_type = 12;</code>
       * @return The moduleType.
       */
      public int getModuleType() {
        return moduleType_;
      }

      public static final int MODULE_SUB_TYPE_FIELD_NUMBER = 13;
      private volatile java.lang.Object moduleSubType_;
      /**
       * <pre>
       *【 类似 N2&amp;C+，N1&amp;B+。。。。光模块类型 】
       * </pre>
       *
       * <code>string module_sub_type = 13;</code>
       * @return The moduleSubType.
       */
      public java.lang.String getModuleSubType() {
        java.lang.Object ref = moduleSubType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          moduleSubType_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *【 类似 N2&amp;C+，N1&amp;B+。。。。光模块类型 】
       * </pre>
       *
       * <code>string module_sub_type = 13;</code>
       * @return The bytes for moduleSubType.
       */
      public com.google.protobuf.ByteString
          getModuleSubTypeBytes() {
        java.lang.Object ref = moduleSubType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          moduleSubType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (temperature_ != 0) {
          output.writeInt32(2, temperature_);
        }
        if (supplyVoltage_ != 0) {
          output.writeInt32(3, supplyVoltage_);
        }
        if (channel1Type_ != 0) {
          output.writeInt32(4, channel1Type_);
        }
        if (channel1TxBias_ != 0) {
          output.writeInt32(5, channel1TxBias_);
        }
        if (channel1TxPower_ != 0) {
          output.writeInt32(6, channel1TxPower_);
        }
        if (channel1IdleRssi_ != 0) {
          output.writeInt32(7, channel1IdleRssi_);
        }
        if (channel2Type_ != 0) {
          output.writeInt32(8, channel2Type_);
        }
        if (channel2TxBias_ != 0) {
          output.writeInt32(9, channel2TxBias_);
        }
        if (channel2TxPower_ != 0) {
          output.writeInt32(10, channel2TxPower_);
        }
        if (channel2IdleRssi_ != 0) {
          output.writeInt32(11, channel2IdleRssi_);
        }
        if (moduleType_ != 0) {
          output.writeInt32(12, moduleType_);
        }
        if (!getModuleSubTypeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 13, moduleSubType_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (temperature_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, temperature_);
        }
        if (supplyVoltage_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, supplyVoltage_);
        }
        if (channel1Type_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, channel1Type_);
        }
        if (channel1TxBias_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, channel1TxBias_);
        }
        if (channel1TxPower_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, channel1TxPower_);
        }
        if (channel1IdleRssi_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(7, channel1IdleRssi_);
        }
        if (channel2Type_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(8, channel2Type_);
        }
        if (channel2TxBias_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(9, channel2TxBias_);
        }
        if (channel2TxPower_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(10, channel2TxPower_);
        }
        if (channel2IdleRssi_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(11, channel2IdleRssi_);
        }
        if (moduleType_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(12, moduleType_);
        }
        if (!getModuleSubTypeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, moduleSubType_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver)) {
          return super.equals(obj);
        }
        com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver other = (com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver) obj;

        if (!getName()
            .equals(other.getName())) return false;
        if (getTemperature()
            != other.getTemperature()) return false;
        if (getSupplyVoltage()
            != other.getSupplyVoltage()) return false;
        if (getChannel1Type()
            != other.getChannel1Type()) return false;
        if (getChannel1TxBias()
            != other.getChannel1TxBias()) return false;
        if (getChannel1TxPower()
            != other.getChannel1TxPower()) return false;
        if (getChannel1IdleRssi()
            != other.getChannel1IdleRssi()) return false;
        if (getChannel2Type()
            != other.getChannel2Type()) return false;
        if (getChannel2TxBias()
            != other.getChannel2TxBias()) return false;
        if (getChannel2TxPower()
            != other.getChannel2TxPower()) return false;
        if (getChannel2IdleRssi()
            != other.getChannel2IdleRssi()) return false;
        if (getModuleType()
            != other.getModuleType()) return false;
        if (!getModuleSubType()
            .equals(other.getModuleSubType())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
        hash = (53 * hash) + getTemperature();
        hash = (37 * hash) + SUPPLY_VOLTAGE_FIELD_NUMBER;
        hash = (53 * hash) + getSupplyVoltage();
        hash = (37 * hash) + CHANNEL_1_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getChannel1Type();
        hash = (37 * hash) + CHANNEL_1_TX_BIAS_FIELD_NUMBER;
        hash = (53 * hash) + getChannel1TxBias();
        hash = (37 * hash) + CHANNEL_1_TX_POWER_FIELD_NUMBER;
        hash = (53 * hash) + getChannel1TxPower();
        hash = (37 * hash) + CHANNEL_1_IDLE_RSSI_FIELD_NUMBER;
        hash = (53 * hash) + getChannel1IdleRssi();
        hash = (37 * hash) + CHANNEL_2_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getChannel2Type();
        hash = (37 * hash) + CHANNEL_2_TX_BIAS_FIELD_NUMBER;
        hash = (53 * hash) + getChannel2TxBias();
        hash = (37 * hash) + CHANNEL_2_TX_POWER_FIELD_NUMBER;
        hash = (53 * hash) + getChannel2TxPower();
        hash = (37 * hash) + CHANNEL_2_IDLE_RSSI_FIELD_NUMBER;
        hash = (53 * hash) + getChannel2IdleRssi();
        hash = (37 * hash) + MODULE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getModuleType();
        hash = (37 * hash) + MODULE_SUB_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getModuleSubType().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver)
          com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.class, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder.class);
        }

        // Construct using com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          temperature_ = 0;

          supplyVoltage_ = 0;

          channel1Type_ = 0;

          channel1TxBias_ = 0;

          channel1TxPower_ = 0;

          channel1IdleRssi_ = 0;

          channel2Type_ = 0;

          channel2TxBias_ = 0;

          channel2TxPower_ = 0;

          channel2IdleRssi_ = 0;

          moduleType_ = 0;

          moduleSubType_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_descriptor;
        }

        @java.lang.Override
        public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver getDefaultInstanceForType() {
          return com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.getDefaultInstance();
        }

        @java.lang.Override
        public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver build() {
          com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver buildPartial() {
          com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver result = new com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver(this);
          result.name_ = name_;
          result.temperature_ = temperature_;
          result.supplyVoltage_ = supplyVoltage_;
          result.channel1Type_ = channel1Type_;
          result.channel1TxBias_ = channel1TxBias_;
          result.channel1TxPower_ = channel1TxPower_;
          result.channel1IdleRssi_ = channel1IdleRssi_;
          result.channel2Type_ = channel2Type_;
          result.channel2TxBias_ = channel2TxBias_;
          result.channel2TxPower_ = channel2TxPower_;
          result.channel2IdleRssi_ = channel2IdleRssi_;
          result.moduleType_ = moduleType_;
          result.moduleSubType_ = moduleSubType_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver) {
            return mergeFrom((com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver other) {
          if (other == com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.getTemperature() != 0) {
            setTemperature(other.getTemperature());
          }
          if (other.getSupplyVoltage() != 0) {
            setSupplyVoltage(other.getSupplyVoltage());
          }
          if (other.getChannel1Type() != 0) {
            setChannel1Type(other.getChannel1Type());
          }
          if (other.getChannel1TxBias() != 0) {
            setChannel1TxBias(other.getChannel1TxBias());
          }
          if (other.getChannel1TxPower() != 0) {
            setChannel1TxPower(other.getChannel1TxPower());
          }
          if (other.getChannel1IdleRssi() != 0) {
            setChannel1IdleRssi(other.getChannel1IdleRssi());
          }
          if (other.getChannel2Type() != 0) {
            setChannel2Type(other.getChannel2Type());
          }
          if (other.getChannel2TxBias() != 0) {
            setChannel2TxBias(other.getChannel2TxBias());
          }
          if (other.getChannel2TxPower() != 0) {
            setChannel2TxPower(other.getChannel2TxPower());
          }
          if (other.getChannel2IdleRssi() != 0) {
            setChannel2IdleRssi(other.getChannel2IdleRssi());
          }
          if (other.getModuleType() != 0) {
            setModuleType(other.getModuleType());
          }
          if (!other.getModuleSubType().isEmpty()) {
            moduleSubType_ = other.moduleSubType_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <pre>
         *端口ID名称，格式：Gpon.f.s.p
         * </pre>
         *
         * <code>string name = 1;</code>
         * @return The name.
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *端口ID名称，格式：Gpon.f.s.p
         * </pre>
         *
         * <code>string name = 1;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *端口ID名称，格式：Gpon.f.s.p
         * </pre>
         *
         * <code>string name = 1;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *端口ID名称，格式：Gpon.f.s.p
         * </pre>
         *
         * <code>string name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *端口ID名称，格式：Gpon.f.s.p
         * </pre>
         *
         * <code>string name = 1;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private int temperature_ ;
        /**
         * <pre>
         *光模块温度，单位0.01℃
         * </pre>
         *
         * <code>int32 temperature = 2;</code>
         * @return The temperature.
         */
        public int getTemperature() {
          return temperature_;
        }
        /**
         * <pre>
         *光模块温度，单位0.01℃
         * </pre>
         *
         * <code>int32 temperature = 2;</code>
         * @param value The temperature to set.
         * @return This builder for chaining.
         */
        public Builder setTemperature(int value) {
          
          temperature_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *光模块温度，单位0.01℃
         * </pre>
         *
         * <code>int32 temperature = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearTemperature() {
          
          temperature_ = 0;
          onChanged();
          return this;
        }

        private int supplyVoltage_ ;
        /**
         * <pre>
         *光模块供电电压， 单位0.01V
         * </pre>
         *
         * <code>int32 supply_voltage = 3;</code>
         * @return The supplyVoltage.
         */
        public int getSupplyVoltage() {
          return supplyVoltage_;
        }
        /**
         * <pre>
         *光模块供电电压， 单位0.01V
         * </pre>
         *
         * <code>int32 supply_voltage = 3;</code>
         * @param value The supplyVoltage to set.
         * @return This builder for chaining.
         */
        public Builder setSupplyVoltage(int value) {
          
          supplyVoltage_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *光模块供电电压， 单位0.01V
         * </pre>
         *
         * <code>int32 supply_voltage = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearSupplyVoltage() {
          
          supplyVoltage_ = 0;
          onChanged();
          return this;
        }

        private int channel1Type_ ;
        /**
         * <pre>
         *通道1类型
         * </pre>
         *
         * <code>int32 channel_1_type = 4;</code>
         * @return The channel1Type.
         */
        public int getChannel1Type() {
          return channel1Type_;
        }
        /**
         * <pre>
         *通道1类型
         * </pre>
         *
         * <code>int32 channel_1_type = 4;</code>
         * @param value The channel1Type to set.
         * @return This builder for chaining.
         */
        public Builder setChannel1Type(int value) {
          
          channel1Type_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *通道1类型
         * </pre>
         *
         * <code>int32 channel_1_type = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearChannel1Type() {
          
          channel1Type_ = 0;
          onChanged();
          return this;
        }

        private int channel1TxBias_ ;
        /**
         * <pre>
         *通道1发送偏置电流，单位0.01mA
         * </pre>
         *
         * <code>int32 channel_1_tx_bias = 5;</code>
         * @return The channel1TxBias.
         */
        public int getChannel1TxBias() {
          return channel1TxBias_;
        }
        /**
         * <pre>
         *通道1发送偏置电流，单位0.01mA
         * </pre>
         *
         * <code>int32 channel_1_tx_bias = 5;</code>
         * @param value The channel1TxBias to set.
         * @return This builder for chaining.
         */
        public Builder setChannel1TxBias(int value) {
          
          channel1TxBias_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *通道1发送偏置电流，单位0.01mA
         * </pre>
         *
         * <code>int32 channel_1_tx_bias = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearChannel1TxBias() {
          
          channel1TxBias_ = 0;
          onChanged();
          return this;
        }

        private int channel1TxPower_ ;
        /**
         * <pre>
         *通道1发送功率，单位0.01dBm，
         * </pre>
         *
         * <code>int32 channel_1_tx_power = 6;</code>
         * @return The channel1TxPower.
         */
        public int getChannel1TxPower() {
          return channel1TxPower_;
        }
        /**
         * <pre>
         *通道1发送功率，单位0.01dBm，
         * </pre>
         *
         * <code>int32 channel_1_tx_power = 6;</code>
         * @param value The channel1TxPower to set.
         * @return This builder for chaining.
         */
        public Builder setChannel1TxPower(int value) {
          
          channel1TxPower_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *通道1发送功率，单位0.01dBm，
         * </pre>
         *
         * <code>int32 channel_1_tx_power = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearChannel1TxPower() {
          
          channel1TxPower_ = 0;
          onChanged();
          return this;
        }

        private int channel1IdleRssi_ ;
        /**
         * <pre>
         *通道1空闲时刻的接收光功率，单位0.01dBm 【未连接 onu 时， pon口 接收光功率为 -40db】
         * </pre>
         *
         * <code>int32 channel_1_idle_rssi = 7;</code>
         * @return The channel1IdleRssi.
         */
        public int getChannel1IdleRssi() {
          return channel1IdleRssi_;
        }
        /**
         * <pre>
         *通道1空闲时刻的接收光功率，单位0.01dBm 【未连接 onu 时， pon口 接收光功率为 -40db】
         * </pre>
         *
         * <code>int32 channel_1_idle_rssi = 7;</code>
         * @param value The channel1IdleRssi to set.
         * @return This builder for chaining.
         */
        public Builder setChannel1IdleRssi(int value) {
          
          channel1IdleRssi_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *通道1空闲时刻的接收光功率，单位0.01dBm 【未连接 onu 时， pon口 接收光功率为 -40db】
         * </pre>
         *
         * <code>int32 channel_1_idle_rssi = 7;</code>
         * @return This builder for chaining.
         */
        public Builder clearChannel1IdleRssi() {
          
          channel1IdleRssi_ = 0;
          onChanged();
          return this;
        }

        private int channel2Type_ ;
        /**
         * <pre>
         *通道2类型 【0x01 : GBIC ; 0x02 : SFF ; 0x03 : SFP】
         * </pre>
         *
         * <code>int32 channel_2_type = 8;</code>
         * @return The channel2Type.
         */
        public int getChannel2Type() {
          return channel2Type_;
        }
        /**
         * <pre>
         *通道2类型 【0x01 : GBIC ; 0x02 : SFF ; 0x03 : SFP】
         * </pre>
         *
         * <code>int32 channel_2_type = 8;</code>
         * @param value The channel2Type to set.
         * @return This builder for chaining.
         */
        public Builder setChannel2Type(int value) {
          
          channel2Type_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *通道2类型 【0x01 : GBIC ; 0x02 : SFF ; 0x03 : SFP】
         * </pre>
         *
         * <code>int32 channel_2_type = 8;</code>
         * @return This builder for chaining.
         */
        public Builder clearChannel2Type() {
          
          channel2Type_ = 0;
          onChanged();
          return this;
        }

        private int channel2TxBias_ ;
        /**
         * <pre>
         *通道2发送偏置电流，单位0.01mA
         * </pre>
         *
         * <code>int32 channel_2_tx_bias = 9;</code>
         * @return The channel2TxBias.
         */
        public int getChannel2TxBias() {
          return channel2TxBias_;
        }
        /**
         * <pre>
         *通道2发送偏置电流，单位0.01mA
         * </pre>
         *
         * <code>int32 channel_2_tx_bias = 9;</code>
         * @param value The channel2TxBias to set.
         * @return This builder for chaining.
         */
        public Builder setChannel2TxBias(int value) {
          
          channel2TxBias_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *通道2发送偏置电流，单位0.01mA
         * </pre>
         *
         * <code>int32 channel_2_tx_bias = 9;</code>
         * @return This builder for chaining.
         */
        public Builder clearChannel2TxBias() {
          
          channel2TxBias_ = 0;
          onChanged();
          return this;
        }

        private int channel2TxPower_ ;
        /**
         * <pre>
         *通道2发送功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 channel_2_tx_power = 10;</code>
         * @return The channel2TxPower.
         */
        public int getChannel2TxPower() {
          return channel2TxPower_;
        }
        /**
         * <pre>
         *通道2发送功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 channel_2_tx_power = 10;</code>
         * @param value The channel2TxPower to set.
         * @return This builder for chaining.
         */
        public Builder setChannel2TxPower(int value) {
          
          channel2TxPower_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *通道2发送功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 channel_2_tx_power = 10;</code>
         * @return This builder for chaining.
         */
        public Builder clearChannel2TxPower() {
          
          channel2TxPower_ = 0;
          onChanged();
          return this;
        }

        private int channel2IdleRssi_ ;
        /**
         * <pre>
         *通道2空闲时刻的接收光功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 channel_2_idle_rssi = 11;</code>
         * @return The channel2IdleRssi.
         */
        public int getChannel2IdleRssi() {
          return channel2IdleRssi_;
        }
        /**
         * <pre>
         *通道2空闲时刻的接收光功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 channel_2_idle_rssi = 11;</code>
         * @param value The channel2IdleRssi to set.
         * @return This builder for chaining.
         */
        public Builder setChannel2IdleRssi(int value) {
          
          channel2IdleRssi_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *通道2空闲时刻的接收光功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 channel_2_idle_rssi = 11;</code>
         * @return This builder for chaining.
         */
        public Builder clearChannel2IdleRssi() {
          
          channel2IdleRssi_ = 0;
          onChanged();
          return this;
        }

        private int moduleType_ ;
        /**
         * <pre>
         *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
         * </pre>
         *
         * <code>int32 module_type = 12;</code>
         * @return The moduleType.
         */
        public int getModuleType() {
          return moduleType_;
        }
        /**
         * <pre>
         *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
         * </pre>
         *
         * <code>int32 module_type = 12;</code>
         * @param value The moduleType to set.
         * @return This builder for chaining.
         */
        public Builder setModuleType(int value) {
          
          moduleType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
         * </pre>
         *
         * <code>int32 module_type = 12;</code>
         * @return This builder for chaining.
         */
        public Builder clearModuleType() {
          
          moduleType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object moduleSubType_ = "";
        /**
         * <pre>
         *【 类似 N2&amp;C+，N1&amp;B+。。。。光模块类型 】
         * </pre>
         *
         * <code>string module_sub_type = 13;</code>
         * @return The moduleSubType.
         */
        public java.lang.String getModuleSubType() {
          java.lang.Object ref = moduleSubType_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            moduleSubType_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *【 类似 N2&amp;C+，N1&amp;B+。。。。光模块类型 】
         * </pre>
         *
         * <code>string module_sub_type = 13;</code>
         * @return The bytes for moduleSubType.
         */
        public com.google.protobuf.ByteString
            getModuleSubTypeBytes() {
          java.lang.Object ref = moduleSubType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            moduleSubType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *【 类似 N2&amp;C+，N1&amp;B+。。。。光模块类型 】
         * </pre>
         *
         * <code>string module_sub_type = 13;</code>
         * @param value The moduleSubType to set.
         * @return This builder for chaining.
         */
        public Builder setModuleSubType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          moduleSubType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *【 类似 N2&amp;C+，N1&amp;B+。。。。光模块类型 】
         * </pre>
         *
         * <code>string module_sub_type = 13;</code>
         * @return This builder for chaining.
         */
        public Builder clearModuleSubType() {
          
          moduleSubType_ = getDefaultInstance().getModuleSubType();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *【 类似 N2&amp;C+，N1&amp;B+。。。。光模块类型 】
         * </pre>
         *
         * <code>string module_sub_type = 13;</code>
         * @param value The bytes for moduleSubType to set.
         * @return This builder for chaining.
         */
        public Builder setModuleSubTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          moduleSubType_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver)
      }

      // @@protoc_insertion_point(class_scope:an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver)
      private static final com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver();
      }

      public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<GponOltTransceiver>
          PARSER = new com.google.protobuf.AbstractParser<GponOltTransceiver>() {
        @java.lang.Override
        public GponOltTransceiver parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new GponOltTransceiver(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<GponOltTransceiver> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<GponOltTransceiver> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int GPON_OLT_TRANSCEIVER_FIELD_NUMBER = 1;
    private java.util.List<com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver> gponOltTransceiver_;
    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    public java.util.List<com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver> getGponOltTransceiverList() {
      return gponOltTransceiver_;
    }
    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    public java.util.List<? extends com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder> 
        getGponOltTransceiverOrBuilderList() {
      return gponOltTransceiver_;
    }
    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    public int getGponOltTransceiverCount() {
      return gponOltTransceiver_.size();
    }
    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver getGponOltTransceiver(int index) {
      return gponOltTransceiver_.get(index);
    }
    /**
     * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
     */
    public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder getGponOltTransceiverOrBuilder(
        int index) {
      return gponOltTransceiver_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < gponOltTransceiver_.size(); i++) {
        output.writeMessage(1, gponOltTransceiver_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < gponOltTransceiver_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gponOltTransceiver_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers)) {
        return super.equals(obj);
      }
      com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers other = (com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers) obj;

      if (!getGponOltTransceiverList()
          .equals(other.getGponOltTransceiverList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGponOltTransceiverCount() > 0) {
        hash = (37 * hash) + GPON_OLT_TRANSCEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getGponOltTransceiverList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code an_gpon_olt_transceivers.GponOltTransceivers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:an_gpon_olt_transceivers.GponOltTransceivers)
        com.telemetry.AnGponPmOltTransceivers.GponOltTransceiversOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.class, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.Builder.class);
      }

      // Construct using com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGponOltTransceiverFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (gponOltTransceiverBuilder_ == null) {
          gponOltTransceiver_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gponOltTransceiverBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.telemetry.AnGponPmOltTransceivers.internal_static_an_gpon_olt_transceivers_GponOltTransceivers_descriptor;
      }

      @java.lang.Override
      public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers getDefaultInstanceForType() {
        return com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.getDefaultInstance();
      }

      @java.lang.Override
      public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers build() {
        com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers buildPartial() {
        com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers result = new com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers(this);
        int from_bitField0_ = bitField0_;
        if (gponOltTransceiverBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            gponOltTransceiver_ = java.util.Collections.unmodifiableList(gponOltTransceiver_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gponOltTransceiver_ = gponOltTransceiver_;
        } else {
          result.gponOltTransceiver_ = gponOltTransceiverBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers) {
          return mergeFrom((com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers other) {
        if (other == com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.getDefaultInstance()) return this;
        if (gponOltTransceiverBuilder_ == null) {
          if (!other.gponOltTransceiver_.isEmpty()) {
            if (gponOltTransceiver_.isEmpty()) {
              gponOltTransceiver_ = other.gponOltTransceiver_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGponOltTransceiverIsMutable();
              gponOltTransceiver_.addAll(other.gponOltTransceiver_);
            }
            onChanged();
          }
        } else {
          if (!other.gponOltTransceiver_.isEmpty()) {
            if (gponOltTransceiverBuilder_.isEmpty()) {
              gponOltTransceiverBuilder_.dispose();
              gponOltTransceiverBuilder_ = null;
              gponOltTransceiver_ = other.gponOltTransceiver_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gponOltTransceiverBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGponOltTransceiverFieldBuilder() : null;
            } else {
              gponOltTransceiverBuilder_.addAllMessages(other.gponOltTransceiver_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver> gponOltTransceiver_ =
        java.util.Collections.emptyList();
      private void ensureGponOltTransceiverIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          gponOltTransceiver_ = new java.util.ArrayList<com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver>(gponOltTransceiver_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder> gponOltTransceiverBuilder_;

      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public java.util.List<com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver> getGponOltTransceiverList() {
        if (gponOltTransceiverBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gponOltTransceiver_);
        } else {
          return gponOltTransceiverBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public int getGponOltTransceiverCount() {
        if (gponOltTransceiverBuilder_ == null) {
          return gponOltTransceiver_.size();
        } else {
          return gponOltTransceiverBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver getGponOltTransceiver(int index) {
        if (gponOltTransceiverBuilder_ == null) {
          return gponOltTransceiver_.get(index);
        } else {
          return gponOltTransceiverBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public Builder setGponOltTransceiver(
          int index, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver value) {
        if (gponOltTransceiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGponOltTransceiverIsMutable();
          gponOltTransceiver_.set(index, value);
          onChanged();
        } else {
          gponOltTransceiverBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public Builder setGponOltTransceiver(
          int index, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder builderForValue) {
        if (gponOltTransceiverBuilder_ == null) {
          ensureGponOltTransceiverIsMutable();
          gponOltTransceiver_.set(index, builderForValue.build());
          onChanged();
        } else {
          gponOltTransceiverBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public Builder addGponOltTransceiver(com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver value) {
        if (gponOltTransceiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGponOltTransceiverIsMutable();
          gponOltTransceiver_.add(value);
          onChanged();
        } else {
          gponOltTransceiverBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public Builder addGponOltTransceiver(
          int index, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver value) {
        if (gponOltTransceiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGponOltTransceiverIsMutable();
          gponOltTransceiver_.add(index, value);
          onChanged();
        } else {
          gponOltTransceiverBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public Builder addGponOltTransceiver(
          com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder builderForValue) {
        if (gponOltTransceiverBuilder_ == null) {
          ensureGponOltTransceiverIsMutable();
          gponOltTransceiver_.add(builderForValue.build());
          onChanged();
        } else {
          gponOltTransceiverBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public Builder addGponOltTransceiver(
          int index, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder builderForValue) {
        if (gponOltTransceiverBuilder_ == null) {
          ensureGponOltTransceiverIsMutable();
          gponOltTransceiver_.add(index, builderForValue.build());
          onChanged();
        } else {
          gponOltTransceiverBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public Builder addAllGponOltTransceiver(
          java.lang.Iterable<? extends com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver> values) {
        if (gponOltTransceiverBuilder_ == null) {
          ensureGponOltTransceiverIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gponOltTransceiver_);
          onChanged();
        } else {
          gponOltTransceiverBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public Builder clearGponOltTransceiver() {
        if (gponOltTransceiverBuilder_ == null) {
          gponOltTransceiver_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gponOltTransceiverBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public Builder removeGponOltTransceiver(int index) {
        if (gponOltTransceiverBuilder_ == null) {
          ensureGponOltTransceiverIsMutable();
          gponOltTransceiver_.remove(index);
          onChanged();
        } else {
          gponOltTransceiverBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder getGponOltTransceiverBuilder(
          int index) {
        return getGponOltTransceiverFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder getGponOltTransceiverOrBuilder(
          int index) {
        if (gponOltTransceiverBuilder_ == null) {
          return gponOltTransceiver_.get(index);  } else {
          return gponOltTransceiverBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public java.util.List<? extends com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder> 
           getGponOltTransceiverOrBuilderList() {
        if (gponOltTransceiverBuilder_ != null) {
          return gponOltTransceiverBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gponOltTransceiver_);
        }
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder addGponOltTransceiverBuilder() {
        return getGponOltTransceiverFieldBuilder().addBuilder(
            com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.getDefaultInstance());
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder addGponOltTransceiverBuilder(
          int index) {
        return getGponOltTransceiverFieldBuilder().addBuilder(
            index, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.getDefaultInstance());
      }
      /**
       * <code>repeated .an_gpon_olt_transceivers.GponOltTransceivers.GponOltTransceiver gpon_olt_transceiver = 1;</code>
       */
      public java.util.List<com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder> 
           getGponOltTransceiverBuilderList() {
        return getGponOltTransceiverFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder> 
          getGponOltTransceiverFieldBuilder() {
        if (gponOltTransceiverBuilder_ == null) {
          gponOltTransceiverBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiver.Builder, com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers.GponOltTransceiverOrBuilder>(
                  gponOltTransceiver_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          gponOltTransceiver_ = null;
        }
        return gponOltTransceiverBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:an_gpon_olt_transceivers.GponOltTransceivers)
    }

    // @@protoc_insertion_point(class_scope:an_gpon_olt_transceivers.GponOltTransceivers)
    private static final com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers();
    }

    public static com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GponOltTransceivers>
        PARSER = new com.google.protobuf.AbstractParser<GponOltTransceivers>() {
      @java.lang.Override
      public GponOltTransceivers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GponOltTransceivers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GponOltTransceivers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GponOltTransceivers> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.telemetry.AnGponPmOltTransceivers.GponOltTransceivers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_an_gpon_olt_transceivers_GponOltTransceivers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_an_gpon_olt_transceivers_GponOltTransceivers_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!an-gpon-pm-olt-transceivers.proto\022\030an_" +
      "gpon_olt_transceivers\"\315\003\n\023GponOltTransce" +
      "ivers\022^\n\024gpon_olt_transceiver\030\001 \003(\0132@.an" +
      "_gpon_olt_transceivers.GponOltTransceive" +
      "rs.GponOltTransceiver\032\325\002\n\022GponOltTransce" +
      "iver\022\014\n\004name\030\001 \001(\t\022\023\n\013temperature\030\002 \001(\005\022" +
      "\026\n\016supply_voltage\030\003 \001(\005\022\026\n\016channel_1_typ" +
      "e\030\004 \001(\005\022\031\n\021channel_1_tx_bias\030\005 \001(\005\022\032\n\022ch" +
      "annel_1_tx_power\030\006 \001(\005\022\033\n\023channel_1_idle" +
      "_rssi\030\007 \001(\005\022\026\n\016channel_2_type\030\010 \001(\005\022\031\n\021c" +
      "hannel_2_tx_bias\030\t \001(\005\022\032\n\022channel_2_tx_p" +
      "ower\030\n \001(\005\022\033\n\023channel_2_idle_rssi\030\013 \001(\005\022" +
      "\023\n\013module_type\030\014 \001(\005\022\027\n\017module_sub_type\030" +
      "\r \001(\tB\017\n\rcom.telemetryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_an_gpon_olt_transceivers_GponOltTransceivers_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_an_gpon_olt_transceivers_GponOltTransceivers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_an_gpon_olt_transceivers_GponOltTransceivers_descriptor,
        new java.lang.String[] { "GponOltTransceiver", });
    internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_descriptor =
      internal_static_an_gpon_olt_transceivers_GponOltTransceivers_descriptor.getNestedTypes().get(0);
    internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_an_gpon_olt_transceivers_GponOltTransceivers_GponOltTransceiver_descriptor,
        new java.lang.String[] { "Name", "Temperature", "SupplyVoltage", "Channel1Type", "Channel1TxBias", "Channel1TxPower", "Channel1IdleRssi", "Channel2Type", "Channel2TxBias", "Channel2TxPower", "Channel2IdleRssi", "ModuleType", "ModuleSubType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
