// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: an-gpon-onu-transceivers.proto

package com.telemetry;

public final class AnGponOnuTransceivers {
  private AnGponOnuTransceivers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GponOnuTransceiversOrBuilder extends
      // @@protoc_insertion_point(interface_extends:an_gpon_onu_transceivers.GponOnuTransceivers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    java.util.List<com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver> 
        getGponOnuTransceiverList();
    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver getGponOnuTransceiver(int index);
    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    int getGponOnuTransceiverCount();
    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    java.util.List<? extends com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder> 
        getGponOnuTransceiverOrBuilderList();
    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder getGponOnuTransceiverOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code an_gpon_onu_transceivers.GponOnuTransceivers}
   */
  public  static final class GponOnuTransceivers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:an_gpon_onu_transceivers.GponOnuTransceivers)
      GponOnuTransceiversOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GponOnuTransceivers.newBuilder() to construct.
    private GponOnuTransceivers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GponOnuTransceivers() {
      gponOnuTransceiver_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GponOnuTransceivers();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GponOnuTransceivers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                gponOnuTransceiver_ = new java.util.ArrayList<com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver>();
                mutable_bitField0_ |= 0x00000001;
              }
              gponOnuTransceiver_.add(
                  input.readMessage(com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          gponOnuTransceiver_ = java.util.Collections.unmodifiableList(gponOnuTransceiver_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.class, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.Builder.class);
    }

    public interface GponOnuTransceiverOrBuilder extends
        // @@protoc_insertion_point(interface_extends:an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *ONU名称，格式：v-ani.f.s.p.onuid
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      java.lang.String getName();
      /**
       * <pre>
       *ONU名称，格式：v-ani.f.s.p.onuid
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <pre>
       *接收光功率，单位0.01dBm
       * </pre>
       *
       * <code>int32 optical_unit_rx_power = 2;</code>
       * @return The opticalUnitRxPower.
       */
      int getOpticalUnitRxPower();

      /**
       * <pre>
       *发送光功率，单位0.01dBm
       * </pre>
       *
       * <code>int32 optical_unit_tx_power = 3;</code>
       * @return The opticalUnitTxPower.
       */
      int getOpticalUnitTxPower();

      /**
       * <pre>
       *端口的偏置电流， 单位：0.01mA。
       * </pre>
       *
       * <code>int32 optical_unit_laser_bias_current = 4;</code>
       * @return The opticalUnitLaserBiasCurrent.
       */
      int getOpticalUnitLaserBiasCurrent();

      /**
       * <pre>
       *光模块当前的温度，单位：0.01℃。
       * </pre>
       *
       * <code>int32 optical_unit_temperature = 5;</code>
       * @return The opticalUnitTemperature.
       */
      int getOpticalUnitTemperature();

      /**
       * <pre>
       *光模块当前的电压，单位是：0.01V。
       * </pre>
       *
       * <code>int32 optical_unit_voltage = 6;</code>
       * @return The opticalUnitVoltage.
       */
      int getOpticalUnitVoltage();

      /**
       * <pre>
       *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
       * </pre>
       *
       * <code>int32 module_type = 7;</code>
       * @return The moduleType.
       */
      int getModuleType();

      /**
       * <pre>
       *光模块子类型
       * </pre>
       *
       * <code>string module_sub_type = 8;</code>
       * @return The moduleSubType.
       */
      java.lang.String getModuleSubType();
      /**
       * <pre>
       *光模块子类型
       * </pre>
       *
       * <code>string module_sub_type = 8;</code>
       * @return The bytes for moduleSubType.
       */
      com.google.protobuf.ByteString
          getModuleSubTypeBytes();
    }
    /**
     * Protobuf type {@code an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver}
     */
    public  static final class GponOnuTransceiver extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver)
        GponOnuTransceiverOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use GponOnuTransceiver.newBuilder() to construct.
      private GponOnuTransceiver(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private GponOnuTransceiver() {
        name_ = "";
        moduleSubType_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new GponOnuTransceiver();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private GponOnuTransceiver(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 16: {

                opticalUnitRxPower_ = input.readInt32();
                break;
              }
              case 24: {

                opticalUnitTxPower_ = input.readInt32();
                break;
              }
              case 32: {

                opticalUnitLaserBiasCurrent_ = input.readInt32();
                break;
              }
              case 40: {

                opticalUnitTemperature_ = input.readInt32();
                break;
              }
              case 48: {

                opticalUnitVoltage_ = input.readInt32();
                break;
              }
              case 56: {

                moduleType_ = input.readInt32();
                break;
              }
              case 66: {
                java.lang.String s = input.readStringRequireUtf8();

                moduleSubType_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.class, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <pre>
       *ONU名称，格式：v-ani.f.s.p.onuid
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *ONU名称，格式：v-ani.f.s.p.onuid
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int OPTICAL_UNIT_RX_POWER_FIELD_NUMBER = 2;
      private int opticalUnitRxPower_;
      /**
       * <pre>
       *接收光功率，单位0.01dBm
       * </pre>
       *
       * <code>int32 optical_unit_rx_power = 2;</code>
       * @return The opticalUnitRxPower.
       */
      public int getOpticalUnitRxPower() {
        return opticalUnitRxPower_;
      }

      public static final int OPTICAL_UNIT_TX_POWER_FIELD_NUMBER = 3;
      private int opticalUnitTxPower_;
      /**
       * <pre>
       *发送光功率，单位0.01dBm
       * </pre>
       *
       * <code>int32 optical_unit_tx_power = 3;</code>
       * @return The opticalUnitTxPower.
       */
      public int getOpticalUnitTxPower() {
        return opticalUnitTxPower_;
      }

      public static final int OPTICAL_UNIT_LASER_BIAS_CURRENT_FIELD_NUMBER = 4;
      private int opticalUnitLaserBiasCurrent_;
      /**
       * <pre>
       *端口的偏置电流， 单位：0.01mA。
       * </pre>
       *
       * <code>int32 optical_unit_laser_bias_current = 4;</code>
       * @return The opticalUnitLaserBiasCurrent.
       */
      public int getOpticalUnitLaserBiasCurrent() {
        return opticalUnitLaserBiasCurrent_;
      }

      public static final int OPTICAL_UNIT_TEMPERATURE_FIELD_NUMBER = 5;
      private int opticalUnitTemperature_;
      /**
       * <pre>
       *光模块当前的温度，单位：0.01℃。
       * </pre>
       *
       * <code>int32 optical_unit_temperature = 5;</code>
       * @return The opticalUnitTemperature.
       */
      public int getOpticalUnitTemperature() {
        return opticalUnitTemperature_;
      }

      public static final int OPTICAL_UNIT_VOLTAGE_FIELD_NUMBER = 6;
      private int opticalUnitVoltage_;
      /**
       * <pre>
       *光模块当前的电压，单位是：0.01V。
       * </pre>
       *
       * <code>int32 optical_unit_voltage = 6;</code>
       * @return The opticalUnitVoltage.
       */
      public int getOpticalUnitVoltage() {
        return opticalUnitVoltage_;
      }

      public static final int MODULE_TYPE_FIELD_NUMBER = 7;
      private int moduleType_;
      /**
       * <pre>
       *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
       * </pre>
       *
       * <code>int32 module_type = 7;</code>
       * @return The moduleType.
       */
      public int getModuleType() {
        return moduleType_;
      }

      public static final int MODULE_SUB_TYPE_FIELD_NUMBER = 8;
      private volatile java.lang.Object moduleSubType_;
      /**
       * <pre>
       *光模块子类型
       * </pre>
       *
       * <code>string module_sub_type = 8;</code>
       * @return The moduleSubType.
       */
      public java.lang.String getModuleSubType() {
        java.lang.Object ref = moduleSubType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          moduleSubType_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *光模块子类型
       * </pre>
       *
       * <code>string module_sub_type = 8;</code>
       * @return The bytes for moduleSubType.
       */
      public com.google.protobuf.ByteString
          getModuleSubTypeBytes() {
        java.lang.Object ref = moduleSubType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          moduleSubType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (opticalUnitRxPower_ != 0) {
          output.writeInt32(2, opticalUnitRxPower_);
        }
        if (opticalUnitTxPower_ != 0) {
          output.writeInt32(3, opticalUnitTxPower_);
        }
        if (opticalUnitLaserBiasCurrent_ != 0) {
          output.writeInt32(4, opticalUnitLaserBiasCurrent_);
        }
        if (opticalUnitTemperature_ != 0) {
          output.writeInt32(5, opticalUnitTemperature_);
        }
        if (opticalUnitVoltage_ != 0) {
          output.writeInt32(6, opticalUnitVoltage_);
        }
        if (moduleType_ != 0) {
          output.writeInt32(7, moduleType_);
        }
        if (!getModuleSubTypeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 8, moduleSubType_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (opticalUnitRxPower_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, opticalUnitRxPower_);
        }
        if (opticalUnitTxPower_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, opticalUnitTxPower_);
        }
        if (opticalUnitLaserBiasCurrent_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, opticalUnitLaserBiasCurrent_);
        }
        if (opticalUnitTemperature_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, opticalUnitTemperature_);
        }
        if (opticalUnitVoltage_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, opticalUnitVoltage_);
        }
        if (moduleType_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(7, moduleType_);
        }
        if (!getModuleSubTypeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, moduleSubType_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver)) {
          return super.equals(obj);
        }
        com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver other = (com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver) obj;

        if (!getName()
            .equals(other.getName())) return false;
        if (getOpticalUnitRxPower()
            != other.getOpticalUnitRxPower()) return false;
        if (getOpticalUnitTxPower()
            != other.getOpticalUnitTxPower()) return false;
        if (getOpticalUnitLaserBiasCurrent()
            != other.getOpticalUnitLaserBiasCurrent()) return false;
        if (getOpticalUnitTemperature()
            != other.getOpticalUnitTemperature()) return false;
        if (getOpticalUnitVoltage()
            != other.getOpticalUnitVoltage()) return false;
        if (getModuleType()
            != other.getModuleType()) return false;
        if (!getModuleSubType()
            .equals(other.getModuleSubType())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + OPTICAL_UNIT_RX_POWER_FIELD_NUMBER;
        hash = (53 * hash) + getOpticalUnitRxPower();
        hash = (37 * hash) + OPTICAL_UNIT_TX_POWER_FIELD_NUMBER;
        hash = (53 * hash) + getOpticalUnitTxPower();
        hash = (37 * hash) + OPTICAL_UNIT_LASER_BIAS_CURRENT_FIELD_NUMBER;
        hash = (53 * hash) + getOpticalUnitLaserBiasCurrent();
        hash = (37 * hash) + OPTICAL_UNIT_TEMPERATURE_FIELD_NUMBER;
        hash = (53 * hash) + getOpticalUnitTemperature();
        hash = (37 * hash) + OPTICAL_UNIT_VOLTAGE_FIELD_NUMBER;
        hash = (53 * hash) + getOpticalUnitVoltage();
        hash = (37 * hash) + MODULE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getModuleType();
        hash = (37 * hash) + MODULE_SUB_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getModuleSubType().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver)
          com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.class, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder.class);
        }

        // Construct using com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          opticalUnitRxPower_ = 0;

          opticalUnitTxPower_ = 0;

          opticalUnitLaserBiasCurrent_ = 0;

          opticalUnitTemperature_ = 0;

          opticalUnitVoltage_ = 0;

          moduleType_ = 0;

          moduleSubType_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_descriptor;
        }

        @java.lang.Override
        public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver getDefaultInstanceForType() {
          return com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.getDefaultInstance();
        }

        @java.lang.Override
        public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver build() {
          com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver buildPartial() {
          com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver result = new com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver(this);
          result.name_ = name_;
          result.opticalUnitRxPower_ = opticalUnitRxPower_;
          result.opticalUnitTxPower_ = opticalUnitTxPower_;
          result.opticalUnitLaserBiasCurrent_ = opticalUnitLaserBiasCurrent_;
          result.opticalUnitTemperature_ = opticalUnitTemperature_;
          result.opticalUnitVoltage_ = opticalUnitVoltage_;
          result.moduleType_ = moduleType_;
          result.moduleSubType_ = moduleSubType_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver) {
            return mergeFrom((com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver other) {
          if (other == com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.getOpticalUnitRxPower() != 0) {
            setOpticalUnitRxPower(other.getOpticalUnitRxPower());
          }
          if (other.getOpticalUnitTxPower() != 0) {
            setOpticalUnitTxPower(other.getOpticalUnitTxPower());
          }
          if (other.getOpticalUnitLaserBiasCurrent() != 0) {
            setOpticalUnitLaserBiasCurrent(other.getOpticalUnitLaserBiasCurrent());
          }
          if (other.getOpticalUnitTemperature() != 0) {
            setOpticalUnitTemperature(other.getOpticalUnitTemperature());
          }
          if (other.getOpticalUnitVoltage() != 0) {
            setOpticalUnitVoltage(other.getOpticalUnitVoltage());
          }
          if (other.getModuleType() != 0) {
            setModuleType(other.getModuleType());
          }
          if (!other.getModuleSubType().isEmpty()) {
            moduleSubType_ = other.moduleSubType_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <pre>
         *ONU名称，格式：v-ani.f.s.p.onuid
         * </pre>
         *
         * <code>string name = 1;</code>
         * @return The name.
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *ONU名称，格式：v-ani.f.s.p.onuid
         * </pre>
         *
         * <code>string name = 1;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *ONU名称，格式：v-ani.f.s.p.onuid
         * </pre>
         *
         * <code>string name = 1;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *ONU名称，格式：v-ani.f.s.p.onuid
         * </pre>
         *
         * <code>string name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *ONU名称，格式：v-ani.f.s.p.onuid
         * </pre>
         *
         * <code>string name = 1;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private int opticalUnitRxPower_ ;
        /**
         * <pre>
         *接收光功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 optical_unit_rx_power = 2;</code>
         * @return The opticalUnitRxPower.
         */
        public int getOpticalUnitRxPower() {
          return opticalUnitRxPower_;
        }
        /**
         * <pre>
         *接收光功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 optical_unit_rx_power = 2;</code>
         * @param value The opticalUnitRxPower to set.
         * @return This builder for chaining.
         */
        public Builder setOpticalUnitRxPower(int value) {
          
          opticalUnitRxPower_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *接收光功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 optical_unit_rx_power = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearOpticalUnitRxPower() {
          
          opticalUnitRxPower_ = 0;
          onChanged();
          return this;
        }

        private int opticalUnitTxPower_ ;
        /**
         * <pre>
         *发送光功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 optical_unit_tx_power = 3;</code>
         * @return The opticalUnitTxPower.
         */
        public int getOpticalUnitTxPower() {
          return opticalUnitTxPower_;
        }
        /**
         * <pre>
         *发送光功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 optical_unit_tx_power = 3;</code>
         * @param value The opticalUnitTxPower to set.
         * @return This builder for chaining.
         */
        public Builder setOpticalUnitTxPower(int value) {
          
          opticalUnitTxPower_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *发送光功率，单位0.01dBm
         * </pre>
         *
         * <code>int32 optical_unit_tx_power = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearOpticalUnitTxPower() {
          
          opticalUnitTxPower_ = 0;
          onChanged();
          return this;
        }

        private int opticalUnitLaserBiasCurrent_ ;
        /**
         * <pre>
         *端口的偏置电流， 单位：0.01mA。
         * </pre>
         *
         * <code>int32 optical_unit_laser_bias_current = 4;</code>
         * @return The opticalUnitLaserBiasCurrent.
         */
        public int getOpticalUnitLaserBiasCurrent() {
          return opticalUnitLaserBiasCurrent_;
        }
        /**
         * <pre>
         *端口的偏置电流， 单位：0.01mA。
         * </pre>
         *
         * <code>int32 optical_unit_laser_bias_current = 4;</code>
         * @param value The opticalUnitLaserBiasCurrent to set.
         * @return This builder for chaining.
         */
        public Builder setOpticalUnitLaserBiasCurrent(int value) {
          
          opticalUnitLaserBiasCurrent_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *端口的偏置电流， 单位：0.01mA。
         * </pre>
         *
         * <code>int32 optical_unit_laser_bias_current = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearOpticalUnitLaserBiasCurrent() {
          
          opticalUnitLaserBiasCurrent_ = 0;
          onChanged();
          return this;
        }

        private int opticalUnitTemperature_ ;
        /**
         * <pre>
         *光模块当前的温度，单位：0.01℃。
         * </pre>
         *
         * <code>int32 optical_unit_temperature = 5;</code>
         * @return The opticalUnitTemperature.
         */
        public int getOpticalUnitTemperature() {
          return opticalUnitTemperature_;
        }
        /**
         * <pre>
         *光模块当前的温度，单位：0.01℃。
         * </pre>
         *
         * <code>int32 optical_unit_temperature = 5;</code>
         * @param value The opticalUnitTemperature to set.
         * @return This builder for chaining.
         */
        public Builder setOpticalUnitTemperature(int value) {
          
          opticalUnitTemperature_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *光模块当前的温度，单位：0.01℃。
         * </pre>
         *
         * <code>int32 optical_unit_temperature = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearOpticalUnitTemperature() {
          
          opticalUnitTemperature_ = 0;
          onChanged();
          return this;
        }

        private int opticalUnitVoltage_ ;
        /**
         * <pre>
         *光模块当前的电压，单位是：0.01V。
         * </pre>
         *
         * <code>int32 optical_unit_voltage = 6;</code>
         * @return The opticalUnitVoltage.
         */
        public int getOpticalUnitVoltage() {
          return opticalUnitVoltage_;
        }
        /**
         * <pre>
         *光模块当前的电压，单位是：0.01V。
         * </pre>
         *
         * <code>int32 optical_unit_voltage = 6;</code>
         * @param value The opticalUnitVoltage to set.
         * @return This builder for chaining.
         */
        public Builder setOpticalUnitVoltage(int value) {
          
          opticalUnitVoltage_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *光模块当前的电压，单位是：0.01V。
         * </pre>
         *
         * <code>int32 optical_unit_voltage = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearOpticalUnitVoltage() {
          
          opticalUnitVoltage_ = 0;
          onChanged();
          return this;
        }

        private int moduleType_ ;
        /**
         * <pre>
         *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
         * </pre>
         *
         * <code>int32 module_type = 7;</code>
         * @return The moduleType.
         */
        public int getModuleType() {
          return moduleType_;
        }
        /**
         * <pre>
         *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
         * </pre>
         *
         * <code>int32 module_type = 7;</code>
         * @param value The moduleType to set.
         * @return This builder for chaining.
         */
        public Builder setModuleType(int value) {
          
          moduleType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *光模块类型,0:unknown,1:gpon,2:xg-pon,3:xgs-pon,4:gpon-and-xgpon,5:gpon-and-xgspon,-1:invalid
         * </pre>
         *
         * <code>int32 module_type = 7;</code>
         * @return This builder for chaining.
         */
        public Builder clearModuleType() {
          
          moduleType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object moduleSubType_ = "";
        /**
         * <pre>
         *光模块子类型
         * </pre>
         *
         * <code>string module_sub_type = 8;</code>
         * @return The moduleSubType.
         */
        public java.lang.String getModuleSubType() {
          java.lang.Object ref = moduleSubType_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            moduleSubType_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *光模块子类型
         * </pre>
         *
         * <code>string module_sub_type = 8;</code>
         * @return The bytes for moduleSubType.
         */
        public com.google.protobuf.ByteString
            getModuleSubTypeBytes() {
          java.lang.Object ref = moduleSubType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            moduleSubType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *光模块子类型
         * </pre>
         *
         * <code>string module_sub_type = 8;</code>
         * @param value The moduleSubType to set.
         * @return This builder for chaining.
         */
        public Builder setModuleSubType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          moduleSubType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *光模块子类型
         * </pre>
         *
         * <code>string module_sub_type = 8;</code>
         * @return This builder for chaining.
         */
        public Builder clearModuleSubType() {
          
          moduleSubType_ = getDefaultInstance().getModuleSubType();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *光模块子类型
         * </pre>
         *
         * <code>string module_sub_type = 8;</code>
         * @param value The bytes for moduleSubType to set.
         * @return This builder for chaining.
         */
        public Builder setModuleSubTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          moduleSubType_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver)
      }

      // @@protoc_insertion_point(class_scope:an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver)
      private static final com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver();
      }

      public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<GponOnuTransceiver>
          PARSER = new com.google.protobuf.AbstractParser<GponOnuTransceiver>() {
        @java.lang.Override
        public GponOnuTransceiver parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new GponOnuTransceiver(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<GponOnuTransceiver> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<GponOnuTransceiver> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int GPON_ONU_TRANSCEIVER_FIELD_NUMBER = 1;
    private java.util.List<com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver> gponOnuTransceiver_;
    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    public java.util.List<com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver> getGponOnuTransceiverList() {
      return gponOnuTransceiver_;
    }
    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    public java.util.List<? extends com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder> 
        getGponOnuTransceiverOrBuilderList() {
      return gponOnuTransceiver_;
    }
    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    public int getGponOnuTransceiverCount() {
      return gponOnuTransceiver_.size();
    }
    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver getGponOnuTransceiver(int index) {
      return gponOnuTransceiver_.get(index);
    }
    /**
     * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
     */
    public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder getGponOnuTransceiverOrBuilder(
        int index) {
      return gponOnuTransceiver_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < gponOnuTransceiver_.size(); i++) {
        output.writeMessage(1, gponOnuTransceiver_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < gponOnuTransceiver_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gponOnuTransceiver_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers)) {
        return super.equals(obj);
      }
      com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers other = (com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers) obj;

      if (!getGponOnuTransceiverList()
          .equals(other.getGponOnuTransceiverList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGponOnuTransceiverCount() > 0) {
        hash = (37 * hash) + GPON_ONU_TRANSCEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getGponOnuTransceiverList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code an_gpon_onu_transceivers.GponOnuTransceivers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:an_gpon_onu_transceivers.GponOnuTransceivers)
        com.telemetry.AnGponOnuTransceivers.GponOnuTransceiversOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.class, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.Builder.class);
      }

      // Construct using com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGponOnuTransceiverFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (gponOnuTransceiverBuilder_ == null) {
          gponOnuTransceiver_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gponOnuTransceiverBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.telemetry.AnGponOnuTransceivers.internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_descriptor;
      }

      @java.lang.Override
      public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers getDefaultInstanceForType() {
        return com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.getDefaultInstance();
      }

      @java.lang.Override
      public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers build() {
        com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers buildPartial() {
        com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers result = new com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers(this);
        int from_bitField0_ = bitField0_;
        if (gponOnuTransceiverBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            gponOnuTransceiver_ = java.util.Collections.unmodifiableList(gponOnuTransceiver_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gponOnuTransceiver_ = gponOnuTransceiver_;
        } else {
          result.gponOnuTransceiver_ = gponOnuTransceiverBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers) {
          return mergeFrom((com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers other) {
        if (other == com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.getDefaultInstance()) return this;
        if (gponOnuTransceiverBuilder_ == null) {
          if (!other.gponOnuTransceiver_.isEmpty()) {
            if (gponOnuTransceiver_.isEmpty()) {
              gponOnuTransceiver_ = other.gponOnuTransceiver_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGponOnuTransceiverIsMutable();
              gponOnuTransceiver_.addAll(other.gponOnuTransceiver_);
            }
            onChanged();
          }
        } else {
          if (!other.gponOnuTransceiver_.isEmpty()) {
            if (gponOnuTransceiverBuilder_.isEmpty()) {
              gponOnuTransceiverBuilder_.dispose();
              gponOnuTransceiverBuilder_ = null;
              gponOnuTransceiver_ = other.gponOnuTransceiver_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gponOnuTransceiverBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGponOnuTransceiverFieldBuilder() : null;
            } else {
              gponOnuTransceiverBuilder_.addAllMessages(other.gponOnuTransceiver_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver> gponOnuTransceiver_ =
        java.util.Collections.emptyList();
      private void ensureGponOnuTransceiverIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          gponOnuTransceiver_ = new java.util.ArrayList<com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver>(gponOnuTransceiver_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder> gponOnuTransceiverBuilder_;

      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public java.util.List<com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver> getGponOnuTransceiverList() {
        if (gponOnuTransceiverBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gponOnuTransceiver_);
        } else {
          return gponOnuTransceiverBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public int getGponOnuTransceiverCount() {
        if (gponOnuTransceiverBuilder_ == null) {
          return gponOnuTransceiver_.size();
        } else {
          return gponOnuTransceiverBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver getGponOnuTransceiver(int index) {
        if (gponOnuTransceiverBuilder_ == null) {
          return gponOnuTransceiver_.get(index);
        } else {
          return gponOnuTransceiverBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public Builder setGponOnuTransceiver(
          int index, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver value) {
        if (gponOnuTransceiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGponOnuTransceiverIsMutable();
          gponOnuTransceiver_.set(index, value);
          onChanged();
        } else {
          gponOnuTransceiverBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public Builder setGponOnuTransceiver(
          int index, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder builderForValue) {
        if (gponOnuTransceiverBuilder_ == null) {
          ensureGponOnuTransceiverIsMutable();
          gponOnuTransceiver_.set(index, builderForValue.build());
          onChanged();
        } else {
          gponOnuTransceiverBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public Builder addGponOnuTransceiver(com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver value) {
        if (gponOnuTransceiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGponOnuTransceiverIsMutable();
          gponOnuTransceiver_.add(value);
          onChanged();
        } else {
          gponOnuTransceiverBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public Builder addGponOnuTransceiver(
          int index, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver value) {
        if (gponOnuTransceiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGponOnuTransceiverIsMutable();
          gponOnuTransceiver_.add(index, value);
          onChanged();
        } else {
          gponOnuTransceiverBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public Builder addGponOnuTransceiver(
          com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder builderForValue) {
        if (gponOnuTransceiverBuilder_ == null) {
          ensureGponOnuTransceiverIsMutable();
          gponOnuTransceiver_.add(builderForValue.build());
          onChanged();
        } else {
          gponOnuTransceiverBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public Builder addGponOnuTransceiver(
          int index, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder builderForValue) {
        if (gponOnuTransceiverBuilder_ == null) {
          ensureGponOnuTransceiverIsMutable();
          gponOnuTransceiver_.add(index, builderForValue.build());
          onChanged();
        } else {
          gponOnuTransceiverBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public Builder addAllGponOnuTransceiver(
          java.lang.Iterable<? extends com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver> values) {
        if (gponOnuTransceiverBuilder_ == null) {
          ensureGponOnuTransceiverIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gponOnuTransceiver_);
          onChanged();
        } else {
          gponOnuTransceiverBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public Builder clearGponOnuTransceiver() {
        if (gponOnuTransceiverBuilder_ == null) {
          gponOnuTransceiver_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gponOnuTransceiverBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public Builder removeGponOnuTransceiver(int index) {
        if (gponOnuTransceiverBuilder_ == null) {
          ensureGponOnuTransceiverIsMutable();
          gponOnuTransceiver_.remove(index);
          onChanged();
        } else {
          gponOnuTransceiverBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder getGponOnuTransceiverBuilder(
          int index) {
        return getGponOnuTransceiverFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder getGponOnuTransceiverOrBuilder(
          int index) {
        if (gponOnuTransceiverBuilder_ == null) {
          return gponOnuTransceiver_.get(index);  } else {
          return gponOnuTransceiverBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public java.util.List<? extends com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder> 
           getGponOnuTransceiverOrBuilderList() {
        if (gponOnuTransceiverBuilder_ != null) {
          return gponOnuTransceiverBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gponOnuTransceiver_);
        }
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder addGponOnuTransceiverBuilder() {
        return getGponOnuTransceiverFieldBuilder().addBuilder(
            com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.getDefaultInstance());
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder addGponOnuTransceiverBuilder(
          int index) {
        return getGponOnuTransceiverFieldBuilder().addBuilder(
            index, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.getDefaultInstance());
      }
      /**
       * <code>repeated .an_gpon_onu_transceivers.GponOnuTransceivers.GponOnuTransceiver gpon_onu_transceiver = 1;</code>
       */
      public java.util.List<com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder> 
           getGponOnuTransceiverBuilderList() {
        return getGponOnuTransceiverFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder> 
          getGponOnuTransceiverFieldBuilder() {
        if (gponOnuTransceiverBuilder_ == null) {
          gponOnuTransceiverBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiver.Builder, com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers.GponOnuTransceiverOrBuilder>(
                  gponOnuTransceiver_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          gponOnuTransceiver_ = null;
        }
        return gponOnuTransceiverBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:an_gpon_onu_transceivers.GponOnuTransceivers)
    }

    // @@protoc_insertion_point(class_scope:an_gpon_onu_transceivers.GponOnuTransceivers)
    private static final com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers();
    }

    public static com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GponOnuTransceivers>
        PARSER = new com.google.protobuf.AbstractParser<GponOnuTransceivers>() {
      @java.lang.Override
      public GponOnuTransceivers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GponOnuTransceivers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GponOnuTransceivers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GponOnuTransceivers> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.telemetry.AnGponOnuTransceivers.GponOnuTransceivers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036an-gpon-onu-transceivers.proto\022\030an_gpo" +
      "n_onu_transceivers\"\357\002\n\023GponOnuTransceive" +
      "rs\022^\n\024gpon_onu_transceiver\030\001 \003(\0132@.an_gp" +
      "on_onu_transceivers.GponOnuTransceivers." +
      "GponOnuTransceiver\032\367\001\n\022GponOnuTransceive" +
      "r\022\014\n\004name\030\001 \001(\t\022\035\n\025optical_unit_rx_power" +
      "\030\002 \001(\005\022\035\n\025optical_unit_tx_power\030\003 \001(\005\022\'\n" +
      "\037optical_unit_laser_bias_current\030\004 \001(\005\022 " +
      "\n\030optical_unit_temperature\030\005 \001(\005\022\034\n\024opti" +
      "cal_unit_voltage\030\006 \001(\005\022\023\n\013module_type\030\007 " +
      "\001(\005\022\027\n\017module_sub_type\030\010 \001(\tB\017\n\rcom.tele" +
      "metryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_descriptor,
        new java.lang.String[] { "GponOnuTransceiver", });
    internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_descriptor =
      internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_descriptor.getNestedTypes().get(0);
    internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_an_gpon_onu_transceivers_GponOnuTransceivers_GponOnuTransceiver_descriptor,
        new java.lang.String[] { "Name", "OpticalUnitRxPower", "OpticalUnitTxPower", "OpticalUnitLaserBiasCurrent", "OpticalUnitTemperature", "OpticalUnitVoltage", "ModuleType", "ModuleSubType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
