// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gn-http-kpi-index.proto

package com.telemetry;

public final class GnHttpKpiIndex {
  private GnHttpKpiIndex() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HttpKpiIndexesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gn_http_kpi_index.HttpKpiIndexes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    java.util.List<com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex> 
        getHttpKpiIndexList();
    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex getHttpKpiIndex(int index);
    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    int getHttpKpiIndexCount();
    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    java.util.List<? extends com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder> 
        getHttpKpiIndexOrBuilderList();
    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder getHttpKpiIndexOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gn_http_kpi_index.HttpKpiIndexes}
   */
  public  static final class HttpKpiIndexes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gn_http_kpi_index.HttpKpiIndexes)
      HttpKpiIndexesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HttpKpiIndexes.newBuilder() to construct.
    private HttpKpiIndexes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HttpKpiIndexes() {
      httpKpiIndex_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HttpKpiIndexes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HttpKpiIndexes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                httpKpiIndex_ = new java.util.ArrayList<com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex>();
                mutable_bitField0_ |= 0x00000001;
              }
              httpKpiIndex_.add(
                  input.readMessage(com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          httpKpiIndex_ = java.util.Collections.unmodifiableList(httpKpiIndex_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.class, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.Builder.class);
    }

    public interface HttpKpiIndexOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint32 start_time = 1[json_name = "start-time"];</code>
       * @return The startTime.
       */
      int getStartTime();

      /**
       * <code>uint32 end_time = 2[json_name = "end-time"];</code>
       * @return The endTime.
       */
      int getEndTime();

      /**
       * <code>string client_location = 3[json_name = "client-location"];</code>
       * @return The clientLocation.
       */
      java.lang.String getClientLocation();
      /**
       * <code>string client_location = 3[json_name = "client-location"];</code>
       * @return The bytes for clientLocation.
       */
      com.google.protobuf.ByteString
          getClientLocationBytes();

      /**
       * <code>string client_mac_address = 4[json_name = "client-mac-address"];</code>
       * @return The clientMacAddress.
       */
      java.lang.String getClientMacAddress();
      /**
       * <code>string client_mac_address = 4[json_name = "client-mac-address"];</code>
       * @return The bytes for clientMacAddress.
       */
      com.google.protobuf.ByteString
          getClientMacAddressBytes();

      /**
       * <code>string uuid = 5[json_name = "uuid"];</code>
       * @return The uuid.
       */
      java.lang.String getUuid();
      /**
       * <code>string uuid = 5[json_name = "uuid"];</code>
       * @return The bytes for uuid.
       */
      com.google.protobuf.ByteString
          getUuidBytes();

      /**
       * <code>uint32 application_main_type = 6[json_name = "application-main-type"];</code>
       * @return The applicationMainType.
       */
      int getApplicationMainType();

      /**
       * <code>uint32 application_sub_type = 7[json_name = "application-sub-type"];</code>
       * @return The applicationSubType.
       */
      int getApplicationSubType();

      /**
       * <code>uint32 get_cnt = 8[json_name = "get-cnt"];</code>
       * @return The getCnt.
       */
      int getGetCnt();

      /**
       * <code>uint32 get_succ_cnt = 9[json_name = "get-succ-cnt"];</code>
       * @return The getSuccCnt.
       */
      int getGetSuccCnt();

      /**
       * <code>float first_get_delay_avg = 10[json_name = "first-get-delay-avg"];</code>
       * @return The firstGetDelayAvg.
       */
      float getFirstGetDelayAvg();

      /**
       * <code>uint32 first_get_succ_cnt = 11[json_name = "first-get-succ-cnt"];</code>
       * @return The firstGetSuccCnt.
       */
      int getFirstGetSuccCnt();
    }
    /**
     * Protobuf type {@code gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex}
     */
    public  static final class HttpKpiIndex extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex)
        HttpKpiIndexOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use HttpKpiIndex.newBuilder() to construct.
      private HttpKpiIndex(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private HttpKpiIndex() {
        clientLocation_ = "";
        clientMacAddress_ = "";
        uuid_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new HttpKpiIndex();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private HttpKpiIndex(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                startTime_ = input.readUInt32();
                break;
              }
              case 16: {

                endTime_ = input.readUInt32();
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                clientLocation_ = s;
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                clientMacAddress_ = s;
                break;
              }
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();

                uuid_ = s;
                break;
              }
              case 48: {

                applicationMainType_ = input.readUInt32();
                break;
              }
              case 56: {

                applicationSubType_ = input.readUInt32();
                break;
              }
              case 64: {

                getCnt_ = input.readUInt32();
                break;
              }
              case 72: {

                getSuccCnt_ = input.readUInt32();
                break;
              }
              case 85: {

                firstGetDelayAvg_ = input.readFloat();
                break;
              }
              case 88: {

                firstGetSuccCnt_ = input.readUInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.class, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder.class);
      }

      public static final int START_TIME_FIELD_NUMBER = 1;
      private int startTime_;
      /**
       * <code>uint32 start_time = 1[json_name = "start-time"];</code>
       * @return The startTime.
       */
      public int getStartTime() {
        return startTime_;
      }

      public static final int END_TIME_FIELD_NUMBER = 2;
      private int endTime_;
      /**
       * <code>uint32 end_time = 2[json_name = "end-time"];</code>
       * @return The endTime.
       */
      public int getEndTime() {
        return endTime_;
      }

      public static final int CLIENT_LOCATION_FIELD_NUMBER = 3;
      private volatile java.lang.Object clientLocation_;
      /**
       * <code>string client_location = 3[json_name = "client-location"];</code>
       * @return The clientLocation.
       */
      public java.lang.String getClientLocation() {
        java.lang.Object ref = clientLocation_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientLocation_ = s;
          return s;
        }
      }
      /**
       * <code>string client_location = 3[json_name = "client-location"];</code>
       * @return The bytes for clientLocation.
       */
      public com.google.protobuf.ByteString
          getClientLocationBytes() {
        java.lang.Object ref = clientLocation_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientLocation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CLIENT_MAC_ADDRESS_FIELD_NUMBER = 4;
      private volatile java.lang.Object clientMacAddress_;
      /**
       * <code>string client_mac_address = 4[json_name = "client-mac-address"];</code>
       * @return The clientMacAddress.
       */
      public java.lang.String getClientMacAddress() {
        java.lang.Object ref = clientMacAddress_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientMacAddress_ = s;
          return s;
        }
      }
      /**
       * <code>string client_mac_address = 4[json_name = "client-mac-address"];</code>
       * @return The bytes for clientMacAddress.
       */
      public com.google.protobuf.ByteString
          getClientMacAddressBytes() {
        java.lang.Object ref = clientMacAddress_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientMacAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int UUID_FIELD_NUMBER = 5;
      private volatile java.lang.Object uuid_;
      /**
       * <code>string uuid = 5[json_name = "uuid"];</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        }
      }
      /**
       * <code>string uuid = 5[json_name = "uuid"];</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int APPLICATION_MAIN_TYPE_FIELD_NUMBER = 6;
      private int applicationMainType_;
      /**
       * <code>uint32 application_main_type = 6[json_name = "application-main-type"];</code>
       * @return The applicationMainType.
       */
      public int getApplicationMainType() {
        return applicationMainType_;
      }

      public static final int APPLICATION_SUB_TYPE_FIELD_NUMBER = 7;
      private int applicationSubType_;
      /**
       * <code>uint32 application_sub_type = 7[json_name = "application-sub-type"];</code>
       * @return The applicationSubType.
       */
      public int getApplicationSubType() {
        return applicationSubType_;
      }

      public static final int GET_CNT_FIELD_NUMBER = 8;
      private int getCnt_;
      /**
       * <code>uint32 get_cnt = 8[json_name = "get-cnt"];</code>
       * @return The getCnt.
       */
      public int getGetCnt() {
        return getCnt_;
      }

      public static final int GET_SUCC_CNT_FIELD_NUMBER = 9;
      private int getSuccCnt_;
      /**
       * <code>uint32 get_succ_cnt = 9[json_name = "get-succ-cnt"];</code>
       * @return The getSuccCnt.
       */
      public int getGetSuccCnt() {
        return getSuccCnt_;
      }

      public static final int FIRST_GET_DELAY_AVG_FIELD_NUMBER = 10;
      private float firstGetDelayAvg_;
      /**
       * <code>float first_get_delay_avg = 10[json_name = "first-get-delay-avg"];</code>
       * @return The firstGetDelayAvg.
       */
      public float getFirstGetDelayAvg() {
        return firstGetDelayAvg_;
      }

      public static final int FIRST_GET_SUCC_CNT_FIELD_NUMBER = 11;
      private int firstGetSuccCnt_;
      /**
       * <code>uint32 first_get_succ_cnt = 11[json_name = "first-get-succ-cnt"];</code>
       * @return The firstGetSuccCnt.
       */
      public int getFirstGetSuccCnt() {
        return firstGetSuccCnt_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (startTime_ != 0) {
          output.writeUInt32(1, startTime_);
        }
        if (endTime_ != 0) {
          output.writeUInt32(2, endTime_);
        }
        if (!getClientLocationBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientLocation_);
        }
        if (!getClientMacAddressBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientMacAddress_);
        }
        if (!getUuidBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, uuid_);
        }
        if (applicationMainType_ != 0) {
          output.writeUInt32(6, applicationMainType_);
        }
        if (applicationSubType_ != 0) {
          output.writeUInt32(7, applicationSubType_);
        }
        if (getCnt_ != 0) {
          output.writeUInt32(8, getCnt_);
        }
        if (getSuccCnt_ != 0) {
          output.writeUInt32(9, getSuccCnt_);
        }
        if (firstGetDelayAvg_ != 0F) {
          output.writeFloat(10, firstGetDelayAvg_);
        }
        if (firstGetSuccCnt_ != 0) {
          output.writeUInt32(11, firstGetSuccCnt_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (startTime_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, startTime_);
        }
        if (endTime_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, endTime_);
        }
        if (!getClientLocationBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientLocation_);
        }
        if (!getClientMacAddressBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientMacAddress_);
        }
        if (!getUuidBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, uuid_);
        }
        if (applicationMainType_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(6, applicationMainType_);
        }
        if (applicationSubType_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(7, applicationSubType_);
        }
        if (getCnt_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(8, getCnt_);
        }
        if (getSuccCnt_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(9, getSuccCnt_);
        }
        if (firstGetDelayAvg_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(10, firstGetDelayAvg_);
        }
        if (firstGetSuccCnt_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(11, firstGetSuccCnt_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex)) {
          return super.equals(obj);
        }
        com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex other = (com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex) obj;

        if (getStartTime()
            != other.getStartTime()) return false;
        if (getEndTime()
            != other.getEndTime()) return false;
        if (!getClientLocation()
            .equals(other.getClientLocation())) return false;
        if (!getClientMacAddress()
            .equals(other.getClientMacAddress())) return false;
        if (!getUuid()
            .equals(other.getUuid())) return false;
        if (getApplicationMainType()
            != other.getApplicationMainType()) return false;
        if (getApplicationSubType()
            != other.getApplicationSubType()) return false;
        if (getGetCnt()
            != other.getGetCnt()) return false;
        if (getGetSuccCnt()
            != other.getGetSuccCnt()) return false;
        if (java.lang.Float.floatToIntBits(getFirstGetDelayAvg())
            != java.lang.Float.floatToIntBits(
                other.getFirstGetDelayAvg())) return false;
        if (getFirstGetSuccCnt()
            != other.getFirstGetSuccCnt()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + START_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getStartTime();
        hash = (37 * hash) + END_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getEndTime();
        hash = (37 * hash) + CLIENT_LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getClientLocation().hashCode();
        hash = (37 * hash) + CLIENT_MAC_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getClientMacAddress().hashCode();
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
        hash = (37 * hash) + APPLICATION_MAIN_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getApplicationMainType();
        hash = (37 * hash) + APPLICATION_SUB_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getApplicationSubType();
        hash = (37 * hash) + GET_CNT_FIELD_NUMBER;
        hash = (53 * hash) + getGetCnt();
        hash = (37 * hash) + GET_SUCC_CNT_FIELD_NUMBER;
        hash = (53 * hash) + getGetSuccCnt();
        hash = (37 * hash) + FIRST_GET_DELAY_AVG_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFirstGetDelayAvg());
        hash = (37 * hash) + FIRST_GET_SUCC_CNT_FIELD_NUMBER;
        hash = (53 * hash) + getFirstGetSuccCnt();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex)
          com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.class, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder.class);
        }

        // Construct using com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          startTime_ = 0;

          endTime_ = 0;

          clientLocation_ = "";

          clientMacAddress_ = "";

          uuid_ = "";

          applicationMainType_ = 0;

          applicationSubType_ = 0;

          getCnt_ = 0;

          getSuccCnt_ = 0;

          firstGetDelayAvg_ = 0F;

          firstGetSuccCnt_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_descriptor;
        }

        @java.lang.Override
        public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex getDefaultInstanceForType() {
          return com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.getDefaultInstance();
        }

        @java.lang.Override
        public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex build() {
          com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex buildPartial() {
          com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex result = new com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex(this);
          result.startTime_ = startTime_;
          result.endTime_ = endTime_;
          result.clientLocation_ = clientLocation_;
          result.clientMacAddress_ = clientMacAddress_;
          result.uuid_ = uuid_;
          result.applicationMainType_ = applicationMainType_;
          result.applicationSubType_ = applicationSubType_;
          result.getCnt_ = getCnt_;
          result.getSuccCnt_ = getSuccCnt_;
          result.firstGetDelayAvg_ = firstGetDelayAvg_;
          result.firstGetSuccCnt_ = firstGetSuccCnt_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex) {
            return mergeFrom((com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex other) {
          if (other == com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.getDefaultInstance()) return this;
          if (other.getStartTime() != 0) {
            setStartTime(other.getStartTime());
          }
          if (other.getEndTime() != 0) {
            setEndTime(other.getEndTime());
          }
          if (!other.getClientLocation().isEmpty()) {
            clientLocation_ = other.clientLocation_;
            onChanged();
          }
          if (!other.getClientMacAddress().isEmpty()) {
            clientMacAddress_ = other.clientMacAddress_;
            onChanged();
          }
          if (!other.getUuid().isEmpty()) {
            uuid_ = other.uuid_;
            onChanged();
          }
          if (other.getApplicationMainType() != 0) {
            setApplicationMainType(other.getApplicationMainType());
          }
          if (other.getApplicationSubType() != 0) {
            setApplicationSubType(other.getApplicationSubType());
          }
          if (other.getGetCnt() != 0) {
            setGetCnt(other.getGetCnt());
          }
          if (other.getGetSuccCnt() != 0) {
            setGetSuccCnt(other.getGetSuccCnt());
          }
          if (other.getFirstGetDelayAvg() != 0F) {
            setFirstGetDelayAvg(other.getFirstGetDelayAvg());
          }
          if (other.getFirstGetSuccCnt() != 0) {
            setFirstGetSuccCnt(other.getFirstGetSuccCnt());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int startTime_ ;
        /**
         * <code>uint32 start_time = 1[json_name = "start-time"];</code>
         * @return The startTime.
         */
        public int getStartTime() {
          return startTime_;
        }
        /**
         * <code>uint32 start_time = 1[json_name = "start-time"];</code>
         * @param value The startTime to set.
         * @return This builder for chaining.
         */
        public Builder setStartTime(int value) {
          
          startTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 start_time = 1[json_name = "start-time"];</code>
         * @return This builder for chaining.
         */
        public Builder clearStartTime() {
          
          startTime_ = 0;
          onChanged();
          return this;
        }

        private int endTime_ ;
        /**
         * <code>uint32 end_time = 2[json_name = "end-time"];</code>
         * @return The endTime.
         */
        public int getEndTime() {
          return endTime_;
        }
        /**
         * <code>uint32 end_time = 2[json_name = "end-time"];</code>
         * @param value The endTime to set.
         * @return This builder for chaining.
         */
        public Builder setEndTime(int value) {
          
          endTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 end_time = 2[json_name = "end-time"];</code>
         * @return This builder for chaining.
         */
        public Builder clearEndTime() {
          
          endTime_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object clientLocation_ = "";
        /**
         * <code>string client_location = 3[json_name = "client-location"];</code>
         * @return The clientLocation.
         */
        public java.lang.String getClientLocation() {
          java.lang.Object ref = clientLocation_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientLocation_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string client_location = 3[json_name = "client-location"];</code>
         * @return The bytes for clientLocation.
         */
        public com.google.protobuf.ByteString
            getClientLocationBytes() {
          java.lang.Object ref = clientLocation_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            clientLocation_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string client_location = 3[json_name = "client-location"];</code>
         * @param value The clientLocation to set.
         * @return This builder for chaining.
         */
        public Builder setClientLocation(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          clientLocation_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string client_location = 3[json_name = "client-location"];</code>
         * @return This builder for chaining.
         */
        public Builder clearClientLocation() {
          
          clientLocation_ = getDefaultInstance().getClientLocation();
          onChanged();
          return this;
        }
        /**
         * <code>string client_location = 3[json_name = "client-location"];</code>
         * @param value The bytes for clientLocation to set.
         * @return This builder for chaining.
         */
        public Builder setClientLocationBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          clientLocation_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object clientMacAddress_ = "";
        /**
         * <code>string client_mac_address = 4[json_name = "client-mac-address"];</code>
         * @return The clientMacAddress.
         */
        public java.lang.String getClientMacAddress() {
          java.lang.Object ref = clientMacAddress_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientMacAddress_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string client_mac_address = 4[json_name = "client-mac-address"];</code>
         * @return The bytes for clientMacAddress.
         */
        public com.google.protobuf.ByteString
            getClientMacAddressBytes() {
          java.lang.Object ref = clientMacAddress_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            clientMacAddress_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string client_mac_address = 4[json_name = "client-mac-address"];</code>
         * @param value The clientMacAddress to set.
         * @return This builder for chaining.
         */
        public Builder setClientMacAddress(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          clientMacAddress_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string client_mac_address = 4[json_name = "client-mac-address"];</code>
         * @return This builder for chaining.
         */
        public Builder clearClientMacAddress() {
          
          clientMacAddress_ = getDefaultInstance().getClientMacAddress();
          onChanged();
          return this;
        }
        /**
         * <code>string client_mac_address = 4[json_name = "client-mac-address"];</code>
         * @param value The bytes for clientMacAddress to set.
         * @return This builder for chaining.
         */
        public Builder setClientMacAddressBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          clientMacAddress_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object uuid_ = "";
        /**
         * <code>string uuid = 5[json_name = "uuid"];</code>
         * @return The uuid.
         */
        public java.lang.String getUuid() {
          java.lang.Object ref = uuid_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uuid_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string uuid = 5[json_name = "uuid"];</code>
         * @return The bytes for uuid.
         */
        public com.google.protobuf.ByteString
            getUuidBytes() {
          java.lang.Object ref = uuid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uuid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string uuid = 5[json_name = "uuid"];</code>
         * @param value The uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuid(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          uuid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string uuid = 5[json_name = "uuid"];</code>
         * @return This builder for chaining.
         */
        public Builder clearUuid() {
          
          uuid_ = getDefaultInstance().getUuid();
          onChanged();
          return this;
        }
        /**
         * <code>string uuid = 5[json_name = "uuid"];</code>
         * @param value The bytes for uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          uuid_ = value;
          onChanged();
          return this;
        }

        private int applicationMainType_ ;
        /**
         * <code>uint32 application_main_type = 6[json_name = "application-main-type"];</code>
         * @return The applicationMainType.
         */
        public int getApplicationMainType() {
          return applicationMainType_;
        }
        /**
         * <code>uint32 application_main_type = 6[json_name = "application-main-type"];</code>
         * @param value The applicationMainType to set.
         * @return This builder for chaining.
         */
        public Builder setApplicationMainType(int value) {
          
          applicationMainType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 application_main_type = 6[json_name = "application-main-type"];</code>
         * @return This builder for chaining.
         */
        public Builder clearApplicationMainType() {
          
          applicationMainType_ = 0;
          onChanged();
          return this;
        }

        private int applicationSubType_ ;
        /**
         * <code>uint32 application_sub_type = 7[json_name = "application-sub-type"];</code>
         * @return The applicationSubType.
         */
        public int getApplicationSubType() {
          return applicationSubType_;
        }
        /**
         * <code>uint32 application_sub_type = 7[json_name = "application-sub-type"];</code>
         * @param value The applicationSubType to set.
         * @return This builder for chaining.
         */
        public Builder setApplicationSubType(int value) {
          
          applicationSubType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 application_sub_type = 7[json_name = "application-sub-type"];</code>
         * @return This builder for chaining.
         */
        public Builder clearApplicationSubType() {
          
          applicationSubType_ = 0;
          onChanged();
          return this;
        }

        private int getCnt_ ;
        /**
         * <code>uint32 get_cnt = 8[json_name = "get-cnt"];</code>
         * @return The getCnt.
         */
        public int getGetCnt() {
          return getCnt_;
        }
        /**
         * <code>uint32 get_cnt = 8[json_name = "get-cnt"];</code>
         * @param value The getCnt to set.
         * @return This builder for chaining.
         */
        public Builder setGetCnt(int value) {
          
          getCnt_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 get_cnt = 8[json_name = "get-cnt"];</code>
         * @return This builder for chaining.
         */
        public Builder clearGetCnt() {
          
          getCnt_ = 0;
          onChanged();
          return this;
        }

        private int getSuccCnt_ ;
        /**
         * <code>uint32 get_succ_cnt = 9[json_name = "get-succ-cnt"];</code>
         * @return The getSuccCnt.
         */
        public int getGetSuccCnt() {
          return getSuccCnt_;
        }
        /**
         * <code>uint32 get_succ_cnt = 9[json_name = "get-succ-cnt"];</code>
         * @param value The getSuccCnt to set.
         * @return This builder for chaining.
         */
        public Builder setGetSuccCnt(int value) {
          
          getSuccCnt_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 get_succ_cnt = 9[json_name = "get-succ-cnt"];</code>
         * @return This builder for chaining.
         */
        public Builder clearGetSuccCnt() {
          
          getSuccCnt_ = 0;
          onChanged();
          return this;
        }

        private float firstGetDelayAvg_ ;
        /**
         * <code>float first_get_delay_avg = 10[json_name = "first-get-delay-avg"];</code>
         * @return The firstGetDelayAvg.
         */
        public float getFirstGetDelayAvg() {
          return firstGetDelayAvg_;
        }
        /**
         * <code>float first_get_delay_avg = 10[json_name = "first-get-delay-avg"];</code>
         * @param value The firstGetDelayAvg to set.
         * @return This builder for chaining.
         */
        public Builder setFirstGetDelayAvg(float value) {
          
          firstGetDelayAvg_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float first_get_delay_avg = 10[json_name = "first-get-delay-avg"];</code>
         * @return This builder for chaining.
         */
        public Builder clearFirstGetDelayAvg() {
          
          firstGetDelayAvg_ = 0F;
          onChanged();
          return this;
        }

        private int firstGetSuccCnt_ ;
        /**
         * <code>uint32 first_get_succ_cnt = 11[json_name = "first-get-succ-cnt"];</code>
         * @return The firstGetSuccCnt.
         */
        public int getFirstGetSuccCnt() {
          return firstGetSuccCnt_;
        }
        /**
         * <code>uint32 first_get_succ_cnt = 11[json_name = "first-get-succ-cnt"];</code>
         * @param value The firstGetSuccCnt to set.
         * @return This builder for chaining.
         */
        public Builder setFirstGetSuccCnt(int value) {
          
          firstGetSuccCnt_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 first_get_succ_cnt = 11[json_name = "first-get-succ-cnt"];</code>
         * @return This builder for chaining.
         */
        public Builder clearFirstGetSuccCnt() {
          
          firstGetSuccCnt_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex)
      }

      // @@protoc_insertion_point(class_scope:gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex)
      private static final com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex();
      }

      public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<HttpKpiIndex>
          PARSER = new com.google.protobuf.AbstractParser<HttpKpiIndex>() {
        @java.lang.Override
        public HttpKpiIndex parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new HttpKpiIndex(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<HttpKpiIndex> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<HttpKpiIndex> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int HTTP_KPI_INDEX_FIELD_NUMBER = 1;
    private java.util.List<com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex> httpKpiIndex_;
    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    public java.util.List<com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex> getHttpKpiIndexList() {
      return httpKpiIndex_;
    }
    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    public java.util.List<? extends com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder> 
        getHttpKpiIndexOrBuilderList() {
      return httpKpiIndex_;
    }
    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    public int getHttpKpiIndexCount() {
      return httpKpiIndex_.size();
    }
    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex getHttpKpiIndex(int index) {
      return httpKpiIndex_.get(index);
    }
    /**
     * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
     */
    public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder getHttpKpiIndexOrBuilder(
        int index) {
      return httpKpiIndex_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < httpKpiIndex_.size(); i++) {
        output.writeMessage(1, httpKpiIndex_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < httpKpiIndex_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, httpKpiIndex_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.telemetry.GnHttpKpiIndex.HttpKpiIndexes)) {
        return super.equals(obj);
      }
      com.telemetry.GnHttpKpiIndex.HttpKpiIndexes other = (com.telemetry.GnHttpKpiIndex.HttpKpiIndexes) obj;

      if (!getHttpKpiIndexList()
          .equals(other.getHttpKpiIndexList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHttpKpiIndexCount() > 0) {
        hash = (37 * hash) + HTTP_KPI_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getHttpKpiIndexList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.telemetry.GnHttpKpiIndex.HttpKpiIndexes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gn_http_kpi_index.HttpKpiIndexes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gn_http_kpi_index.HttpKpiIndexes)
        com.telemetry.GnHttpKpiIndex.HttpKpiIndexesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.class, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.Builder.class);
      }

      // Construct using com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHttpKpiIndexFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (httpKpiIndexBuilder_ == null) {
          httpKpiIndex_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          httpKpiIndexBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.telemetry.GnHttpKpiIndex.internal_static_gn_http_kpi_index_HttpKpiIndexes_descriptor;
      }

      @java.lang.Override
      public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes getDefaultInstanceForType() {
        return com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.getDefaultInstance();
      }

      @java.lang.Override
      public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes build() {
        com.telemetry.GnHttpKpiIndex.HttpKpiIndexes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes buildPartial() {
        com.telemetry.GnHttpKpiIndex.HttpKpiIndexes result = new com.telemetry.GnHttpKpiIndex.HttpKpiIndexes(this);
        int from_bitField0_ = bitField0_;
        if (httpKpiIndexBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            httpKpiIndex_ = java.util.Collections.unmodifiableList(httpKpiIndex_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.httpKpiIndex_ = httpKpiIndex_;
        } else {
          result.httpKpiIndex_ = httpKpiIndexBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.telemetry.GnHttpKpiIndex.HttpKpiIndexes) {
          return mergeFrom((com.telemetry.GnHttpKpiIndex.HttpKpiIndexes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.telemetry.GnHttpKpiIndex.HttpKpiIndexes other) {
        if (other == com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.getDefaultInstance()) return this;
        if (httpKpiIndexBuilder_ == null) {
          if (!other.httpKpiIndex_.isEmpty()) {
            if (httpKpiIndex_.isEmpty()) {
              httpKpiIndex_ = other.httpKpiIndex_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHttpKpiIndexIsMutable();
              httpKpiIndex_.addAll(other.httpKpiIndex_);
            }
            onChanged();
          }
        } else {
          if (!other.httpKpiIndex_.isEmpty()) {
            if (httpKpiIndexBuilder_.isEmpty()) {
              httpKpiIndexBuilder_.dispose();
              httpKpiIndexBuilder_ = null;
              httpKpiIndex_ = other.httpKpiIndex_;
              bitField0_ = (bitField0_ & ~0x00000001);
              httpKpiIndexBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHttpKpiIndexFieldBuilder() : null;
            } else {
              httpKpiIndexBuilder_.addAllMessages(other.httpKpiIndex_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.telemetry.GnHttpKpiIndex.HttpKpiIndexes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.telemetry.GnHttpKpiIndex.HttpKpiIndexes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex> httpKpiIndex_ =
        java.util.Collections.emptyList();
      private void ensureHttpKpiIndexIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          httpKpiIndex_ = new java.util.ArrayList<com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex>(httpKpiIndex_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder> httpKpiIndexBuilder_;

      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public java.util.List<com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex> getHttpKpiIndexList() {
        if (httpKpiIndexBuilder_ == null) {
          return java.util.Collections.unmodifiableList(httpKpiIndex_);
        } else {
          return httpKpiIndexBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public int getHttpKpiIndexCount() {
        if (httpKpiIndexBuilder_ == null) {
          return httpKpiIndex_.size();
        } else {
          return httpKpiIndexBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex getHttpKpiIndex(int index) {
        if (httpKpiIndexBuilder_ == null) {
          return httpKpiIndex_.get(index);
        } else {
          return httpKpiIndexBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public Builder setHttpKpiIndex(
          int index, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex value) {
        if (httpKpiIndexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpKpiIndexIsMutable();
          httpKpiIndex_.set(index, value);
          onChanged();
        } else {
          httpKpiIndexBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public Builder setHttpKpiIndex(
          int index, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder builderForValue) {
        if (httpKpiIndexBuilder_ == null) {
          ensureHttpKpiIndexIsMutable();
          httpKpiIndex_.set(index, builderForValue.build());
          onChanged();
        } else {
          httpKpiIndexBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public Builder addHttpKpiIndex(com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex value) {
        if (httpKpiIndexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpKpiIndexIsMutable();
          httpKpiIndex_.add(value);
          onChanged();
        } else {
          httpKpiIndexBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public Builder addHttpKpiIndex(
          int index, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex value) {
        if (httpKpiIndexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHttpKpiIndexIsMutable();
          httpKpiIndex_.add(index, value);
          onChanged();
        } else {
          httpKpiIndexBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public Builder addHttpKpiIndex(
          com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder builderForValue) {
        if (httpKpiIndexBuilder_ == null) {
          ensureHttpKpiIndexIsMutable();
          httpKpiIndex_.add(builderForValue.build());
          onChanged();
        } else {
          httpKpiIndexBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public Builder addHttpKpiIndex(
          int index, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder builderForValue) {
        if (httpKpiIndexBuilder_ == null) {
          ensureHttpKpiIndexIsMutable();
          httpKpiIndex_.add(index, builderForValue.build());
          onChanged();
        } else {
          httpKpiIndexBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public Builder addAllHttpKpiIndex(
          java.lang.Iterable<? extends com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex> values) {
        if (httpKpiIndexBuilder_ == null) {
          ensureHttpKpiIndexIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, httpKpiIndex_);
          onChanged();
        } else {
          httpKpiIndexBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public Builder clearHttpKpiIndex() {
        if (httpKpiIndexBuilder_ == null) {
          httpKpiIndex_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          httpKpiIndexBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public Builder removeHttpKpiIndex(int index) {
        if (httpKpiIndexBuilder_ == null) {
          ensureHttpKpiIndexIsMutable();
          httpKpiIndex_.remove(index);
          onChanged();
        } else {
          httpKpiIndexBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder getHttpKpiIndexBuilder(
          int index) {
        return getHttpKpiIndexFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder getHttpKpiIndexOrBuilder(
          int index) {
        if (httpKpiIndexBuilder_ == null) {
          return httpKpiIndex_.get(index);  } else {
          return httpKpiIndexBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public java.util.List<? extends com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder> 
           getHttpKpiIndexOrBuilderList() {
        if (httpKpiIndexBuilder_ != null) {
          return httpKpiIndexBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(httpKpiIndex_);
        }
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder addHttpKpiIndexBuilder() {
        return getHttpKpiIndexFieldBuilder().addBuilder(
            com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.getDefaultInstance());
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder addHttpKpiIndexBuilder(
          int index) {
        return getHttpKpiIndexFieldBuilder().addBuilder(
            index, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.getDefaultInstance());
      }
      /**
       * <code>repeated .gn_http_kpi_index.HttpKpiIndexes.HttpKpiIndex http_kpi_index = 1[json_name = "http-kpi-index"];</code>
       */
      public java.util.List<com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder> 
           getHttpKpiIndexBuilderList() {
        return getHttpKpiIndexFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder> 
          getHttpKpiIndexFieldBuilder() {
        if (httpKpiIndexBuilder_ == null) {
          httpKpiIndexBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndex.Builder, com.telemetry.GnHttpKpiIndex.HttpKpiIndexes.HttpKpiIndexOrBuilder>(
                  httpKpiIndex_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          httpKpiIndex_ = null;
        }
        return httpKpiIndexBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gn_http_kpi_index.HttpKpiIndexes)
    }

    // @@protoc_insertion_point(class_scope:gn_http_kpi_index.HttpKpiIndexes)
    private static final com.telemetry.GnHttpKpiIndex.HttpKpiIndexes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.telemetry.GnHttpKpiIndex.HttpKpiIndexes();
    }

    public static com.telemetry.GnHttpKpiIndex.HttpKpiIndexes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HttpKpiIndexes>
        PARSER = new com.google.protobuf.AbstractParser<HttpKpiIndexes>() {
      @java.lang.Override
      public HttpKpiIndexes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HttpKpiIndexes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HttpKpiIndexes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HttpKpiIndexes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.telemetry.GnHttpKpiIndex.HttpKpiIndexes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gn_http_kpi_index_HttpKpiIndexes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gn_http_kpi_index_HttpKpiIndexes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027gn-http-kpi-index.proto\022\021gn_http_kpi_i" +
      "ndex\"\255\004\n\016HttpKpiIndexes\022V\n\016http_kpi_inde" +
      "x\030\001 \003(\0132..gn_http_kpi_index.HttpKpiIndex" +
      "es.HttpKpiIndexR\016http-kpi-index\032\302\003\n\014Http" +
      "KpiIndex\022\036\n\nstart_time\030\001 \001(\rR\nstart-time" +
      "\022\032\n\010end_time\030\002 \001(\rR\010end-time\022(\n\017client_l" +
      "ocation\030\003 \001(\tR\017client-location\022.\n\022client" +
      "_mac_address\030\004 \001(\tR\022client-mac-address\022\022" +
      "\n\004uuid\030\005 \001(\tR\004uuid\0224\n\025application_main_t" +
      "ype\030\006 \001(\rR\025application-main-type\0222\n\024appl" +
      "ication_sub_type\030\007 \001(\rR\024application-sub-" +
      "type\022\030\n\007get_cnt\030\010 \001(\rR\007get-cnt\022\"\n\014get_su" +
      "cc_cnt\030\t \001(\rR\014get-succ-cnt\0220\n\023first_get_" +
      "delay_avg\030\n \001(\002R\023first-get-delay-avg\022.\n\022" +
      "first_get_succ_cnt\030\013 \001(\rR\022first-get-succ" +
      "-cntB\017\n\rcom.telemetryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gn_http_kpi_index_HttpKpiIndexes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gn_http_kpi_index_HttpKpiIndexes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gn_http_kpi_index_HttpKpiIndexes_descriptor,
        new java.lang.String[] { "HttpKpiIndex", });
    internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_descriptor =
      internal_static_gn_http_kpi_index_HttpKpiIndexes_descriptor.getNestedTypes().get(0);
    internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gn_http_kpi_index_HttpKpiIndexes_HttpKpiIndex_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "ClientLocation", "ClientMacAddress", "Uuid", "ApplicationMainType", "ApplicationSubType", "GetCnt", "GetSuccCnt", "FirstGetDelayAvg", "FirstGetSuccCnt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
