// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gn-port-traffic-statistics.proto

package com.telemetry;

public final class GnPortTrafficStatistics {
  private GnPortTrafficStatistics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PortTrafficStatisticsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gn_port_traffic_statistic.PortTrafficStatistics)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    java.util.List<com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic> 
        getPortTrafficStatisticList();
    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic getPortTrafficStatistic(int index);
    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    int getPortTrafficStatisticCount();
    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    java.util.List<? extends com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder> 
        getPortTrafficStatisticOrBuilderList();
    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder getPortTrafficStatisticOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gn_port_traffic_statistic.PortTrafficStatistics}
   */
  public  static final class PortTrafficStatistics extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gn_port_traffic_statistic.PortTrafficStatistics)
      PortTrafficStatisticsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PortTrafficStatistics.newBuilder() to construct.
    private PortTrafficStatistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PortTrafficStatistics() {
      portTrafficStatistic_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PortTrafficStatistics();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PortTrafficStatistics(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                portTrafficStatistic_ = new java.util.ArrayList<com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic>();
                mutable_bitField0_ |= 0x00000001;
              }
              portTrafficStatistic_.add(
                  input.readMessage(com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          portTrafficStatistic_ = java.util.Collections.unmodifiableList(portTrafficStatistic_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.class, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.Builder.class);
    }

    public interface PortTrafficStatisticOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint32 packet_sniff_rate = 1[json_name = "packet-sniff-rate"];</code>
       * @return The packetSniffRate.
       */
      int getPacketSniffRate();

      /**
       * <code>float sniff_rate = 2[json_name = "sniff-rate"];</code>
       * @return The sniffRate.
       */
      float getSniffRate();

      /**
       * <code>uint32 sniff_packets_cnt = 3[json_name = "sniff-packet-cnt"];</code>
       * @return The sniffPacketsCnt.
       */
      int getSniffPacketsCnt();

      /**
       * <code>uint32 sniff_bytes_cnt = 4[json_name = "sniff-bytes-cnt"];</code>
       * @return The sniffBytesCnt.
       */
      int getSniffBytesCnt();
    }
    /**
     * Protobuf type {@code gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic}
     */
    public  static final class PortTrafficStatistic extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic)
        PortTrafficStatisticOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PortTrafficStatistic.newBuilder() to construct.
      private PortTrafficStatistic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PortTrafficStatistic() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PortTrafficStatistic();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PortTrafficStatistic(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                packetSniffRate_ = input.readUInt32();
                break;
              }
              case 21: {

                sniffRate_ = input.readFloat();
                break;
              }
              case 24: {

                sniffPacketsCnt_ = input.readUInt32();
                break;
              }
              case 32: {

                sniffBytesCnt_ = input.readUInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.class, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder.class);
      }

      public static final int PACKET_SNIFF_RATE_FIELD_NUMBER = 1;
      private int packetSniffRate_;
      /**
       * <code>uint32 packet_sniff_rate = 1[json_name = "packet-sniff-rate"];</code>
       * @return The packetSniffRate.
       */
      public int getPacketSniffRate() {
        return packetSniffRate_;
      }

      public static final int SNIFF_RATE_FIELD_NUMBER = 2;
      private float sniffRate_;
      /**
       * <code>float sniff_rate = 2[json_name = "sniff-rate"];</code>
       * @return The sniffRate.
       */
      public float getSniffRate() {
        return sniffRate_;
      }

      public static final int SNIFF_PACKETS_CNT_FIELD_NUMBER = 3;
      private int sniffPacketsCnt_;
      /**
       * <code>uint32 sniff_packets_cnt = 3[json_name = "sniff-packet-cnt"];</code>
       * @return The sniffPacketsCnt.
       */
      public int getSniffPacketsCnt() {
        return sniffPacketsCnt_;
      }

      public static final int SNIFF_BYTES_CNT_FIELD_NUMBER = 4;
      private int sniffBytesCnt_;
      /**
       * <code>uint32 sniff_bytes_cnt = 4[json_name = "sniff-bytes-cnt"];</code>
       * @return The sniffBytesCnt.
       */
      public int getSniffBytesCnt() {
        return sniffBytesCnt_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (packetSniffRate_ != 0) {
          output.writeUInt32(1, packetSniffRate_);
        }
        if (sniffRate_ != 0F) {
          output.writeFloat(2, sniffRate_);
        }
        if (sniffPacketsCnt_ != 0) {
          output.writeUInt32(3, sniffPacketsCnt_);
        }
        if (sniffBytesCnt_ != 0) {
          output.writeUInt32(4, sniffBytesCnt_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (packetSniffRate_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, packetSniffRate_);
        }
        if (sniffRate_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, sniffRate_);
        }
        if (sniffPacketsCnt_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, sniffPacketsCnt_);
        }
        if (sniffBytesCnt_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, sniffBytesCnt_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic)) {
          return super.equals(obj);
        }
        com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic other = (com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic) obj;

        if (getPacketSniffRate()
            != other.getPacketSniffRate()) return false;
        if (java.lang.Float.floatToIntBits(getSniffRate())
            != java.lang.Float.floatToIntBits(
                other.getSniffRate())) return false;
        if (getSniffPacketsCnt()
            != other.getSniffPacketsCnt()) return false;
        if (getSniffBytesCnt()
            != other.getSniffBytesCnt()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PACKET_SNIFF_RATE_FIELD_NUMBER;
        hash = (53 * hash) + getPacketSniffRate();
        hash = (37 * hash) + SNIFF_RATE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getSniffRate());
        hash = (37 * hash) + SNIFF_PACKETS_CNT_FIELD_NUMBER;
        hash = (53 * hash) + getSniffPacketsCnt();
        hash = (37 * hash) + SNIFF_BYTES_CNT_FIELD_NUMBER;
        hash = (53 * hash) + getSniffBytesCnt();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic)
          com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.class, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder.class);
        }

        // Construct using com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          packetSniffRate_ = 0;

          sniffRate_ = 0F;

          sniffPacketsCnt_ = 0;

          sniffBytesCnt_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_descriptor;
        }

        @java.lang.Override
        public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic getDefaultInstanceForType() {
          return com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.getDefaultInstance();
        }

        @java.lang.Override
        public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic build() {
          com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic buildPartial() {
          com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic result = new com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic(this);
          result.packetSniffRate_ = packetSniffRate_;
          result.sniffRate_ = sniffRate_;
          result.sniffPacketsCnt_ = sniffPacketsCnt_;
          result.sniffBytesCnt_ = sniffBytesCnt_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic) {
            return mergeFrom((com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic other) {
          if (other == com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.getDefaultInstance()) return this;
          if (other.getPacketSniffRate() != 0) {
            setPacketSniffRate(other.getPacketSniffRate());
          }
          if (other.getSniffRate() != 0F) {
            setSniffRate(other.getSniffRate());
          }
          if (other.getSniffPacketsCnt() != 0) {
            setSniffPacketsCnt(other.getSniffPacketsCnt());
          }
          if (other.getSniffBytesCnt() != 0) {
            setSniffBytesCnt(other.getSniffBytesCnt());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int packetSniffRate_ ;
        /**
         * <code>uint32 packet_sniff_rate = 1[json_name = "packet-sniff-rate"];</code>
         * @return The packetSniffRate.
         */
        public int getPacketSniffRate() {
          return packetSniffRate_;
        }
        /**
         * <code>uint32 packet_sniff_rate = 1[json_name = "packet-sniff-rate"];</code>
         * @param value The packetSniffRate to set.
         * @return This builder for chaining.
         */
        public Builder setPacketSniffRate(int value) {
          
          packetSniffRate_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 packet_sniff_rate = 1[json_name = "packet-sniff-rate"];</code>
         * @return This builder for chaining.
         */
        public Builder clearPacketSniffRate() {
          
          packetSniffRate_ = 0;
          onChanged();
          return this;
        }

        private float sniffRate_ ;
        /**
         * <code>float sniff_rate = 2[json_name = "sniff-rate"];</code>
         * @return The sniffRate.
         */
        public float getSniffRate() {
          return sniffRate_;
        }
        /**
         * <code>float sniff_rate = 2[json_name = "sniff-rate"];</code>
         * @param value The sniffRate to set.
         * @return This builder for chaining.
         */
        public Builder setSniffRate(float value) {
          
          sniffRate_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>float sniff_rate = 2[json_name = "sniff-rate"];</code>
         * @return This builder for chaining.
         */
        public Builder clearSniffRate() {
          
          sniffRate_ = 0F;
          onChanged();
          return this;
        }

        private int sniffPacketsCnt_ ;
        /**
         * <code>uint32 sniff_packets_cnt = 3[json_name = "sniff-packet-cnt"];</code>
         * @return The sniffPacketsCnt.
         */
        public int getSniffPacketsCnt() {
          return sniffPacketsCnt_;
        }
        /**
         * <code>uint32 sniff_packets_cnt = 3[json_name = "sniff-packet-cnt"];</code>
         * @param value The sniffPacketsCnt to set.
         * @return This builder for chaining.
         */
        public Builder setSniffPacketsCnt(int value) {
          
          sniffPacketsCnt_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 sniff_packets_cnt = 3[json_name = "sniff-packet-cnt"];</code>
         * @return This builder for chaining.
         */
        public Builder clearSniffPacketsCnt() {
          
          sniffPacketsCnt_ = 0;
          onChanged();
          return this;
        }

        private int sniffBytesCnt_ ;
        /**
         * <code>uint32 sniff_bytes_cnt = 4[json_name = "sniff-bytes-cnt"];</code>
         * @return The sniffBytesCnt.
         */
        public int getSniffBytesCnt() {
          return sniffBytesCnt_;
        }
        /**
         * <code>uint32 sniff_bytes_cnt = 4[json_name = "sniff-bytes-cnt"];</code>
         * @param value The sniffBytesCnt to set.
         * @return This builder for chaining.
         */
        public Builder setSniffBytesCnt(int value) {
          
          sniffBytesCnt_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 sniff_bytes_cnt = 4[json_name = "sniff-bytes-cnt"];</code>
         * @return This builder for chaining.
         */
        public Builder clearSniffBytesCnt() {
          
          sniffBytesCnt_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic)
      }

      // @@protoc_insertion_point(class_scope:gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic)
      private static final com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic();
      }

      public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PortTrafficStatistic>
          PARSER = new com.google.protobuf.AbstractParser<PortTrafficStatistic>() {
        @java.lang.Override
        public PortTrafficStatistic parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PortTrafficStatistic(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PortTrafficStatistic> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PortTrafficStatistic> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PORT_TRAFFIC_STATISTIC_FIELD_NUMBER = 1;
    private java.util.List<com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic> portTrafficStatistic_;
    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    public java.util.List<com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic> getPortTrafficStatisticList() {
      return portTrafficStatistic_;
    }
    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    public java.util.List<? extends com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder> 
        getPortTrafficStatisticOrBuilderList() {
      return portTrafficStatistic_;
    }
    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    public int getPortTrafficStatisticCount() {
      return portTrafficStatistic_.size();
    }
    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic getPortTrafficStatistic(int index) {
      return portTrafficStatistic_.get(index);
    }
    /**
     * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
     */
    public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder getPortTrafficStatisticOrBuilder(
        int index) {
      return portTrafficStatistic_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < portTrafficStatistic_.size(); i++) {
        output.writeMessage(1, portTrafficStatistic_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < portTrafficStatistic_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, portTrafficStatistic_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics)) {
        return super.equals(obj);
      }
      com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics other = (com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics) obj;

      if (!getPortTrafficStatisticList()
          .equals(other.getPortTrafficStatisticList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPortTrafficStatisticCount() > 0) {
        hash = (37 * hash) + PORT_TRAFFIC_STATISTIC_FIELD_NUMBER;
        hash = (53 * hash) + getPortTrafficStatisticList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gn_port_traffic_statistic.PortTrafficStatistics}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gn_port_traffic_statistic.PortTrafficStatistics)
        com.telemetry.GnPortTrafficStatistics.PortTrafficStatisticsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.class, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.Builder.class);
      }

      // Construct using com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPortTrafficStatisticFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (portTrafficStatisticBuilder_ == null) {
          portTrafficStatistic_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          portTrafficStatisticBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.telemetry.GnPortTrafficStatistics.internal_static_gn_port_traffic_statistic_PortTrafficStatistics_descriptor;
      }

      @java.lang.Override
      public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics getDefaultInstanceForType() {
        return com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.getDefaultInstance();
      }

      @java.lang.Override
      public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics build() {
        com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics buildPartial() {
        com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics result = new com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics(this);
        int from_bitField0_ = bitField0_;
        if (portTrafficStatisticBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            portTrafficStatistic_ = java.util.Collections.unmodifiableList(portTrafficStatistic_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.portTrafficStatistic_ = portTrafficStatistic_;
        } else {
          result.portTrafficStatistic_ = portTrafficStatisticBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics) {
          return mergeFrom((com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics other) {
        if (other == com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.getDefaultInstance()) return this;
        if (portTrafficStatisticBuilder_ == null) {
          if (!other.portTrafficStatistic_.isEmpty()) {
            if (portTrafficStatistic_.isEmpty()) {
              portTrafficStatistic_ = other.portTrafficStatistic_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePortTrafficStatisticIsMutable();
              portTrafficStatistic_.addAll(other.portTrafficStatistic_);
            }
            onChanged();
          }
        } else {
          if (!other.portTrafficStatistic_.isEmpty()) {
            if (portTrafficStatisticBuilder_.isEmpty()) {
              portTrafficStatisticBuilder_.dispose();
              portTrafficStatisticBuilder_ = null;
              portTrafficStatistic_ = other.portTrafficStatistic_;
              bitField0_ = (bitField0_ & ~0x00000001);
              portTrafficStatisticBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPortTrafficStatisticFieldBuilder() : null;
            } else {
              portTrafficStatisticBuilder_.addAllMessages(other.portTrafficStatistic_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic> portTrafficStatistic_ =
        java.util.Collections.emptyList();
      private void ensurePortTrafficStatisticIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          portTrafficStatistic_ = new java.util.ArrayList<com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic>(portTrafficStatistic_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder> portTrafficStatisticBuilder_;

      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public java.util.List<com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic> getPortTrafficStatisticList() {
        if (portTrafficStatisticBuilder_ == null) {
          return java.util.Collections.unmodifiableList(portTrafficStatistic_);
        } else {
          return portTrafficStatisticBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public int getPortTrafficStatisticCount() {
        if (portTrafficStatisticBuilder_ == null) {
          return portTrafficStatistic_.size();
        } else {
          return portTrafficStatisticBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic getPortTrafficStatistic(int index) {
        if (portTrafficStatisticBuilder_ == null) {
          return portTrafficStatistic_.get(index);
        } else {
          return portTrafficStatisticBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public Builder setPortTrafficStatistic(
          int index, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic value) {
        if (portTrafficStatisticBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortTrafficStatisticIsMutable();
          portTrafficStatistic_.set(index, value);
          onChanged();
        } else {
          portTrafficStatisticBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public Builder setPortTrafficStatistic(
          int index, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder builderForValue) {
        if (portTrafficStatisticBuilder_ == null) {
          ensurePortTrafficStatisticIsMutable();
          portTrafficStatistic_.set(index, builderForValue.build());
          onChanged();
        } else {
          portTrafficStatisticBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public Builder addPortTrafficStatistic(com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic value) {
        if (portTrafficStatisticBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortTrafficStatisticIsMutable();
          portTrafficStatistic_.add(value);
          onChanged();
        } else {
          portTrafficStatisticBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public Builder addPortTrafficStatistic(
          int index, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic value) {
        if (portTrafficStatisticBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortTrafficStatisticIsMutable();
          portTrafficStatistic_.add(index, value);
          onChanged();
        } else {
          portTrafficStatisticBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public Builder addPortTrafficStatistic(
          com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder builderForValue) {
        if (portTrafficStatisticBuilder_ == null) {
          ensurePortTrafficStatisticIsMutable();
          portTrafficStatistic_.add(builderForValue.build());
          onChanged();
        } else {
          portTrafficStatisticBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public Builder addPortTrafficStatistic(
          int index, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder builderForValue) {
        if (portTrafficStatisticBuilder_ == null) {
          ensurePortTrafficStatisticIsMutable();
          portTrafficStatistic_.add(index, builderForValue.build());
          onChanged();
        } else {
          portTrafficStatisticBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public Builder addAllPortTrafficStatistic(
          java.lang.Iterable<? extends com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic> values) {
        if (portTrafficStatisticBuilder_ == null) {
          ensurePortTrafficStatisticIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, portTrafficStatistic_);
          onChanged();
        } else {
          portTrafficStatisticBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public Builder clearPortTrafficStatistic() {
        if (portTrafficStatisticBuilder_ == null) {
          portTrafficStatistic_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          portTrafficStatisticBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public Builder removePortTrafficStatistic(int index) {
        if (portTrafficStatisticBuilder_ == null) {
          ensurePortTrafficStatisticIsMutable();
          portTrafficStatistic_.remove(index);
          onChanged();
        } else {
          portTrafficStatisticBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder getPortTrafficStatisticBuilder(
          int index) {
        return getPortTrafficStatisticFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder getPortTrafficStatisticOrBuilder(
          int index) {
        if (portTrafficStatisticBuilder_ == null) {
          return portTrafficStatistic_.get(index);  } else {
          return portTrafficStatisticBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public java.util.List<? extends com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder> 
           getPortTrafficStatisticOrBuilderList() {
        if (portTrafficStatisticBuilder_ != null) {
          return portTrafficStatisticBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(portTrafficStatistic_);
        }
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder addPortTrafficStatisticBuilder() {
        return getPortTrafficStatisticFieldBuilder().addBuilder(
            com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.getDefaultInstance());
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder addPortTrafficStatisticBuilder(
          int index) {
        return getPortTrafficStatisticFieldBuilder().addBuilder(
            index, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.getDefaultInstance());
      }
      /**
       * <code>repeated .gn_port_traffic_statistic.PortTrafficStatistics.PortTrafficStatistic port_traffic_statistic = 1[json_name = "port-traffic-statistic"];</code>
       */
      public java.util.List<com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder> 
           getPortTrafficStatisticBuilderList() {
        return getPortTrafficStatisticFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder> 
          getPortTrafficStatisticFieldBuilder() {
        if (portTrafficStatisticBuilder_ == null) {
          portTrafficStatisticBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatistic.Builder, com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics.PortTrafficStatisticOrBuilder>(
                  portTrafficStatistic_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          portTrafficStatistic_ = null;
        }
        return portTrafficStatisticBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gn_port_traffic_statistic.PortTrafficStatistics)
    }

    // @@protoc_insertion_point(class_scope:gn_port_traffic_statistic.PortTrafficStatistics)
    private static final com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics();
    }

    public static com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PortTrafficStatistics>
        PARSER = new com.google.protobuf.AbstractParser<PortTrafficStatistics>() {
      @java.lang.Override
      public PortTrafficStatistics parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PortTrafficStatistics(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PortTrafficStatistics> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PortTrafficStatistics> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.telemetry.GnPortTrafficStatistics.PortTrafficStatistics getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gn_port_traffic_statistic_PortTrafficStatistics_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gn_port_traffic_statistic_PortTrafficStatistics_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n gn-port-traffic-statistics.proto\022\031gn_p" +
      "ort_traffic_statistic\"\324\002\n\025PortTrafficSta" +
      "tistics\022}\n\026port_traffic_statistic\030\001 \003(\0132" +
      "E.gn_port_traffic_statistic.PortTrafficS" +
      "tatistics.PortTrafficStatisticR\026port-tra" +
      "ffic-statistic\032\273\001\n\024PortTrafficStatistic\022" +
      ",\n\021packet_sniff_rate\030\001 \001(\rR\021packet-sniff" +
      "-rate\022\036\n\nsniff_rate\030\002 \001(\002R\nsniff-rate\022+\n" +
      "\021sniff_packets_cnt\030\003 \001(\rR\020sniff-packet-c" +
      "nt\022(\n\017sniff_bytes_cnt\030\004 \001(\rR\017sniff-bytes" +
      "-cntB\017\n\rcom.telemetryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gn_port_traffic_statistic_PortTrafficStatistics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gn_port_traffic_statistic_PortTrafficStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gn_port_traffic_statistic_PortTrafficStatistics_descriptor,
        new java.lang.String[] { "PortTrafficStatistic", });
    internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_descriptor =
      internal_static_gn_port_traffic_statistic_PortTrafficStatistics_descriptor.getNestedTypes().get(0);
    internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gn_port_traffic_statistic_PortTrafficStatistics_PortTrafficStatistic_descriptor,
        new java.lang.String[] { "PacketSniffRate", "SniffRate", "SniffPacketsCnt", "SniffBytesCnt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
