// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gn-terminal-event.proto

package com.telemetry;

public final class GnTerminalEvent {
  private GnTerminalEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TerminalEventsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gn_terminal_event.TerminalEvents)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    java.util.List<com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent> 
        getTerminalEventList();
    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent getTerminalEvent(int index);
    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    int getTerminalEventCount();
    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    java.util.List<? extends com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder> 
        getTerminalEventOrBuilderList();
    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder getTerminalEventOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gn_terminal_event.TerminalEvents}
   */
  public  static final class TerminalEvents extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gn_terminal_event.TerminalEvents)
      TerminalEventsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TerminalEvents.newBuilder() to construct.
    private TerminalEvents(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TerminalEvents() {
      terminalEvent_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TerminalEvents();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TerminalEvents(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                terminalEvent_ = new java.util.ArrayList<com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent>();
                mutable_bitField0_ |= 0x00000001;
              }
              terminalEvent_.add(
                  input.readMessage(com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          terminalEvent_ = java.util.Collections.unmodifiableList(terminalEvent_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.telemetry.GnTerminalEvent.TerminalEvents.class, com.telemetry.GnTerminalEvent.TerminalEvents.Builder.class);
    }

    public interface TerminalEventOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gn_terminal_event.TerminalEvents.TerminalEvent)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint64 event_time = 1[json_name = "event-time"];</code>
       * @return The eventTime.
       */
      long getEventTime();

      /**
       * <code>string client_mac_address = 2[json_name = "client-mac-address"];</code>
       * @return The clientMacAddress.
       */
      java.lang.String getClientMacAddress();
      /**
       * <code>string client_mac_address = 2[json_name = "client-mac-address"];</code>
       * @return The bytes for clientMacAddress.
       */
      com.google.protobuf.ByteString
          getClientMacAddressBytes();

      /**
       * <code>uint32 terminal_type = 3[json_name = "terminal-type"];</code>
       * @return The terminalType.
       */
      int getTerminalType();

      /**
       * <code>string browse_tool = 4[json_name = "browse-tool"];</code>
       * @return The browseTool.
       */
      java.lang.String getBrowseTool();
      /**
       * <code>string browse_tool = 4[json_name = "browse-tool"];</code>
       * @return The bytes for browseTool.
       */
      com.google.protobuf.ByteString
          getBrowseToolBytes();
    }
    /**
     * Protobuf type {@code gn_terminal_event.TerminalEvents.TerminalEvent}
     */
    public  static final class TerminalEvent extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:gn_terminal_event.TerminalEvents.TerminalEvent)
        TerminalEventOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use TerminalEvent.newBuilder() to construct.
      private TerminalEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private TerminalEvent() {
        clientMacAddress_ = "";
        browseTool_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new TerminalEvent();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private TerminalEvent(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                eventTime_ = input.readUInt64();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                clientMacAddress_ = s;
                break;
              }
              case 24: {

                terminalType_ = input.readUInt32();
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                browseTool_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.class, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder.class);
      }

      public static final int EVENT_TIME_FIELD_NUMBER = 1;
      private long eventTime_;
      /**
       * <code>uint64 event_time = 1[json_name = "event-time"];</code>
       * @return The eventTime.
       */
      public long getEventTime() {
        return eventTime_;
      }

      public static final int CLIENT_MAC_ADDRESS_FIELD_NUMBER = 2;
      private volatile java.lang.Object clientMacAddress_;
      /**
       * <code>string client_mac_address = 2[json_name = "client-mac-address"];</code>
       * @return The clientMacAddress.
       */
      public java.lang.String getClientMacAddress() {
        java.lang.Object ref = clientMacAddress_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientMacAddress_ = s;
          return s;
        }
      }
      /**
       * <code>string client_mac_address = 2[json_name = "client-mac-address"];</code>
       * @return The bytes for clientMacAddress.
       */
      public com.google.protobuf.ByteString
          getClientMacAddressBytes() {
        java.lang.Object ref = clientMacAddress_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientMacAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TERMINAL_TYPE_FIELD_NUMBER = 3;
      private int terminalType_;
      /**
       * <code>uint32 terminal_type = 3[json_name = "terminal-type"];</code>
       * @return The terminalType.
       */
      public int getTerminalType() {
        return terminalType_;
      }

      public static final int BROWSE_TOOL_FIELD_NUMBER = 4;
      private volatile java.lang.Object browseTool_;
      /**
       * <code>string browse_tool = 4[json_name = "browse-tool"];</code>
       * @return The browseTool.
       */
      public java.lang.String getBrowseTool() {
        java.lang.Object ref = browseTool_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          browseTool_ = s;
          return s;
        }
      }
      /**
       * <code>string browse_tool = 4[json_name = "browse-tool"];</code>
       * @return The bytes for browseTool.
       */
      public com.google.protobuf.ByteString
          getBrowseToolBytes() {
        java.lang.Object ref = browseTool_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          browseTool_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (eventTime_ != 0L) {
          output.writeUInt64(1, eventTime_);
        }
        if (!getClientMacAddressBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientMacAddress_);
        }
        if (terminalType_ != 0) {
          output.writeUInt32(3, terminalType_);
        }
        if (!getBrowseToolBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, browseTool_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (eventTime_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(1, eventTime_);
        }
        if (!getClientMacAddressBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientMacAddress_);
        }
        if (terminalType_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, terminalType_);
        }
        if (!getBrowseToolBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, browseTool_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent)) {
          return super.equals(obj);
        }
        com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent other = (com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent) obj;

        if (getEventTime()
            != other.getEventTime()) return false;
        if (!getClientMacAddress()
            .equals(other.getClientMacAddress())) return false;
        if (getTerminalType()
            != other.getTerminalType()) return false;
        if (!getBrowseTool()
            .equals(other.getBrowseTool())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + EVENT_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEventTime());
        hash = (37 * hash) + CLIENT_MAC_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getClientMacAddress().hashCode();
        hash = (37 * hash) + TERMINAL_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTerminalType();
        hash = (37 * hash) + BROWSE_TOOL_FIELD_NUMBER;
        hash = (53 * hash) + getBrowseTool().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gn_terminal_event.TerminalEvents.TerminalEvent}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gn_terminal_event.TerminalEvents.TerminalEvent)
          com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.class, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder.class);
        }

        // Construct using com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          eventTime_ = 0L;

          clientMacAddress_ = "";

          terminalType_ = 0;

          browseTool_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_descriptor;
        }

        @java.lang.Override
        public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent getDefaultInstanceForType() {
          return com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.getDefaultInstance();
        }

        @java.lang.Override
        public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent build() {
          com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent buildPartial() {
          com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent result = new com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent(this);
          result.eventTime_ = eventTime_;
          result.clientMacAddress_ = clientMacAddress_;
          result.terminalType_ = terminalType_;
          result.browseTool_ = browseTool_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent) {
            return mergeFrom((com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent other) {
          if (other == com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.getDefaultInstance()) return this;
          if (other.getEventTime() != 0L) {
            setEventTime(other.getEventTime());
          }
          if (!other.getClientMacAddress().isEmpty()) {
            clientMacAddress_ = other.clientMacAddress_;
            onChanged();
          }
          if (other.getTerminalType() != 0) {
            setTerminalType(other.getTerminalType());
          }
          if (!other.getBrowseTool().isEmpty()) {
            browseTool_ = other.browseTool_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long eventTime_ ;
        /**
         * <code>uint64 event_time = 1[json_name = "event-time"];</code>
         * @return The eventTime.
         */
        public long getEventTime() {
          return eventTime_;
        }
        /**
         * <code>uint64 event_time = 1[json_name = "event-time"];</code>
         * @param value The eventTime to set.
         * @return This builder for chaining.
         */
        public Builder setEventTime(long value) {
          
          eventTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint64 event_time = 1[json_name = "event-time"];</code>
         * @return This builder for chaining.
         */
        public Builder clearEventTime() {
          
          eventTime_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object clientMacAddress_ = "";
        /**
         * <code>string client_mac_address = 2[json_name = "client-mac-address"];</code>
         * @return The clientMacAddress.
         */
        public java.lang.String getClientMacAddress() {
          java.lang.Object ref = clientMacAddress_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientMacAddress_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string client_mac_address = 2[json_name = "client-mac-address"];</code>
         * @return The bytes for clientMacAddress.
         */
        public com.google.protobuf.ByteString
            getClientMacAddressBytes() {
          java.lang.Object ref = clientMacAddress_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            clientMacAddress_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string client_mac_address = 2[json_name = "client-mac-address"];</code>
         * @param value The clientMacAddress to set.
         * @return This builder for chaining.
         */
        public Builder setClientMacAddress(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          clientMacAddress_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string client_mac_address = 2[json_name = "client-mac-address"];</code>
         * @return This builder for chaining.
         */
        public Builder clearClientMacAddress() {
          
          clientMacAddress_ = getDefaultInstance().getClientMacAddress();
          onChanged();
          return this;
        }
        /**
         * <code>string client_mac_address = 2[json_name = "client-mac-address"];</code>
         * @param value The bytes for clientMacAddress to set.
         * @return This builder for chaining.
         */
        public Builder setClientMacAddressBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          clientMacAddress_ = value;
          onChanged();
          return this;
        }

        private int terminalType_ ;
        /**
         * <code>uint32 terminal_type = 3[json_name = "terminal-type"];</code>
         * @return The terminalType.
         */
        public int getTerminalType() {
          return terminalType_;
        }
        /**
         * <code>uint32 terminal_type = 3[json_name = "terminal-type"];</code>
         * @param value The terminalType to set.
         * @return This builder for chaining.
         */
        public Builder setTerminalType(int value) {
          
          terminalType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 terminal_type = 3[json_name = "terminal-type"];</code>
         * @return This builder for chaining.
         */
        public Builder clearTerminalType() {
          
          terminalType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object browseTool_ = "";
        /**
         * <code>string browse_tool = 4[json_name = "browse-tool"];</code>
         * @return The browseTool.
         */
        public java.lang.String getBrowseTool() {
          java.lang.Object ref = browseTool_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            browseTool_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string browse_tool = 4[json_name = "browse-tool"];</code>
         * @return The bytes for browseTool.
         */
        public com.google.protobuf.ByteString
            getBrowseToolBytes() {
          java.lang.Object ref = browseTool_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            browseTool_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string browse_tool = 4[json_name = "browse-tool"];</code>
         * @param value The browseTool to set.
         * @return This builder for chaining.
         */
        public Builder setBrowseTool(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          browseTool_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string browse_tool = 4[json_name = "browse-tool"];</code>
         * @return This builder for chaining.
         */
        public Builder clearBrowseTool() {
          
          browseTool_ = getDefaultInstance().getBrowseTool();
          onChanged();
          return this;
        }
        /**
         * <code>string browse_tool = 4[json_name = "browse-tool"];</code>
         * @param value The bytes for browseTool to set.
         * @return This builder for chaining.
         */
        public Builder setBrowseToolBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          browseTool_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:gn_terminal_event.TerminalEvents.TerminalEvent)
      }

      // @@protoc_insertion_point(class_scope:gn_terminal_event.TerminalEvents.TerminalEvent)
      private static final com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent();
      }

      public static com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<TerminalEvent>
          PARSER = new com.google.protobuf.AbstractParser<TerminalEvent>() {
        @java.lang.Override
        public TerminalEvent parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new TerminalEvent(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<TerminalEvent> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<TerminalEvent> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int TERMINAL_EVENT_FIELD_NUMBER = 1;
    private java.util.List<com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent> terminalEvent_;
    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    public java.util.List<com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent> getTerminalEventList() {
      return terminalEvent_;
    }
    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    public java.util.List<? extends com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder> 
        getTerminalEventOrBuilderList() {
      return terminalEvent_;
    }
    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    public int getTerminalEventCount() {
      return terminalEvent_.size();
    }
    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent getTerminalEvent(int index) {
      return terminalEvent_.get(index);
    }
    /**
     * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
     */
    public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder getTerminalEventOrBuilder(
        int index) {
      return terminalEvent_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < terminalEvent_.size(); i++) {
        output.writeMessage(1, terminalEvent_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < terminalEvent_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, terminalEvent_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.telemetry.GnTerminalEvent.TerminalEvents)) {
        return super.equals(obj);
      }
      com.telemetry.GnTerminalEvent.TerminalEvents other = (com.telemetry.GnTerminalEvent.TerminalEvents) obj;

      if (!getTerminalEventList()
          .equals(other.getTerminalEventList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTerminalEventCount() > 0) {
        hash = (37 * hash) + TERMINAL_EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getTerminalEventList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.telemetry.GnTerminalEvent.TerminalEvents parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.telemetry.GnTerminalEvent.TerminalEvents prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gn_terminal_event.TerminalEvents}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gn_terminal_event.TerminalEvents)
        com.telemetry.GnTerminalEvent.TerminalEventsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.telemetry.GnTerminalEvent.TerminalEvents.class, com.telemetry.GnTerminalEvent.TerminalEvents.Builder.class);
      }

      // Construct using com.telemetry.GnTerminalEvent.TerminalEvents.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTerminalEventFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (terminalEventBuilder_ == null) {
          terminalEvent_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          terminalEventBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.telemetry.GnTerminalEvent.internal_static_gn_terminal_event_TerminalEvents_descriptor;
      }

      @java.lang.Override
      public com.telemetry.GnTerminalEvent.TerminalEvents getDefaultInstanceForType() {
        return com.telemetry.GnTerminalEvent.TerminalEvents.getDefaultInstance();
      }

      @java.lang.Override
      public com.telemetry.GnTerminalEvent.TerminalEvents build() {
        com.telemetry.GnTerminalEvent.TerminalEvents result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.telemetry.GnTerminalEvent.TerminalEvents buildPartial() {
        com.telemetry.GnTerminalEvent.TerminalEvents result = new com.telemetry.GnTerminalEvent.TerminalEvents(this);
        int from_bitField0_ = bitField0_;
        if (terminalEventBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            terminalEvent_ = java.util.Collections.unmodifiableList(terminalEvent_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.terminalEvent_ = terminalEvent_;
        } else {
          result.terminalEvent_ = terminalEventBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.telemetry.GnTerminalEvent.TerminalEvents) {
          return mergeFrom((com.telemetry.GnTerminalEvent.TerminalEvents)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.telemetry.GnTerminalEvent.TerminalEvents other) {
        if (other == com.telemetry.GnTerminalEvent.TerminalEvents.getDefaultInstance()) return this;
        if (terminalEventBuilder_ == null) {
          if (!other.terminalEvent_.isEmpty()) {
            if (terminalEvent_.isEmpty()) {
              terminalEvent_ = other.terminalEvent_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTerminalEventIsMutable();
              terminalEvent_.addAll(other.terminalEvent_);
            }
            onChanged();
          }
        } else {
          if (!other.terminalEvent_.isEmpty()) {
            if (terminalEventBuilder_.isEmpty()) {
              terminalEventBuilder_.dispose();
              terminalEventBuilder_ = null;
              terminalEvent_ = other.terminalEvent_;
              bitField0_ = (bitField0_ & ~0x00000001);
              terminalEventBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTerminalEventFieldBuilder() : null;
            } else {
              terminalEventBuilder_.addAllMessages(other.terminalEvent_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.telemetry.GnTerminalEvent.TerminalEvents parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.telemetry.GnTerminalEvent.TerminalEvents) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent> terminalEvent_ =
        java.util.Collections.emptyList();
      private void ensureTerminalEventIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          terminalEvent_ = new java.util.ArrayList<com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent>(terminalEvent_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder> terminalEventBuilder_;

      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public java.util.List<com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent> getTerminalEventList() {
        if (terminalEventBuilder_ == null) {
          return java.util.Collections.unmodifiableList(terminalEvent_);
        } else {
          return terminalEventBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public int getTerminalEventCount() {
        if (terminalEventBuilder_ == null) {
          return terminalEvent_.size();
        } else {
          return terminalEventBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent getTerminalEvent(int index) {
        if (terminalEventBuilder_ == null) {
          return terminalEvent_.get(index);
        } else {
          return terminalEventBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public Builder setTerminalEvent(
          int index, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent value) {
        if (terminalEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTerminalEventIsMutable();
          terminalEvent_.set(index, value);
          onChanged();
        } else {
          terminalEventBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public Builder setTerminalEvent(
          int index, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder builderForValue) {
        if (terminalEventBuilder_ == null) {
          ensureTerminalEventIsMutable();
          terminalEvent_.set(index, builderForValue.build());
          onChanged();
        } else {
          terminalEventBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public Builder addTerminalEvent(com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent value) {
        if (terminalEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTerminalEventIsMutable();
          terminalEvent_.add(value);
          onChanged();
        } else {
          terminalEventBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public Builder addTerminalEvent(
          int index, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent value) {
        if (terminalEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTerminalEventIsMutable();
          terminalEvent_.add(index, value);
          onChanged();
        } else {
          terminalEventBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public Builder addTerminalEvent(
          com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder builderForValue) {
        if (terminalEventBuilder_ == null) {
          ensureTerminalEventIsMutable();
          terminalEvent_.add(builderForValue.build());
          onChanged();
        } else {
          terminalEventBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public Builder addTerminalEvent(
          int index, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder builderForValue) {
        if (terminalEventBuilder_ == null) {
          ensureTerminalEventIsMutable();
          terminalEvent_.add(index, builderForValue.build());
          onChanged();
        } else {
          terminalEventBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public Builder addAllTerminalEvent(
          java.lang.Iterable<? extends com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent> values) {
        if (terminalEventBuilder_ == null) {
          ensureTerminalEventIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, terminalEvent_);
          onChanged();
        } else {
          terminalEventBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public Builder clearTerminalEvent() {
        if (terminalEventBuilder_ == null) {
          terminalEvent_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          terminalEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public Builder removeTerminalEvent(int index) {
        if (terminalEventBuilder_ == null) {
          ensureTerminalEventIsMutable();
          terminalEvent_.remove(index);
          onChanged();
        } else {
          terminalEventBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder getTerminalEventBuilder(
          int index) {
        return getTerminalEventFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder getTerminalEventOrBuilder(
          int index) {
        if (terminalEventBuilder_ == null) {
          return terminalEvent_.get(index);  } else {
          return terminalEventBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public java.util.List<? extends com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder> 
           getTerminalEventOrBuilderList() {
        if (terminalEventBuilder_ != null) {
          return terminalEventBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(terminalEvent_);
        }
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder addTerminalEventBuilder() {
        return getTerminalEventFieldBuilder().addBuilder(
            com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder addTerminalEventBuilder(
          int index) {
        return getTerminalEventFieldBuilder().addBuilder(
            index, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .gn_terminal_event.TerminalEvents.TerminalEvent terminal_event = 1[json_name = "terminal-event"];</code>
       */
      public java.util.List<com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder> 
           getTerminalEventBuilderList() {
        return getTerminalEventFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder> 
          getTerminalEventFieldBuilder() {
        if (terminalEventBuilder_ == null) {
          terminalEventBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEvent.Builder, com.telemetry.GnTerminalEvent.TerminalEvents.TerminalEventOrBuilder>(
                  terminalEvent_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          terminalEvent_ = null;
        }
        return terminalEventBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gn_terminal_event.TerminalEvents)
    }

    // @@protoc_insertion_point(class_scope:gn_terminal_event.TerminalEvents)
    private static final com.telemetry.GnTerminalEvent.TerminalEvents DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.telemetry.GnTerminalEvent.TerminalEvents();
    }

    public static com.telemetry.GnTerminalEvent.TerminalEvents getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TerminalEvents>
        PARSER = new com.google.protobuf.AbstractParser<TerminalEvents>() {
      @java.lang.Override
      public TerminalEvents parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TerminalEvents(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TerminalEvents> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TerminalEvents> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.telemetry.GnTerminalEvent.TerminalEvents getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gn_terminal_event_TerminalEvents_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gn_terminal_event_TerminalEvents_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027gn-terminal-event.proto\022\021gn_terminal_e" +
      "vent\"\223\002\n\016TerminalEvents\022W\n\016terminal_even" +
      "t\030\001 \003(\0132/.gn_terminal_event.TerminalEven" +
      "ts.TerminalEventR\016terminal-event\032\247\001\n\rTer" +
      "minalEvent\022\036\n\nevent_time\030\001 \001(\004R\nevent-ti" +
      "me\022.\n\022client_mac_address\030\002 \001(\tR\022client-m" +
      "ac-address\022$\n\rterminal_type\030\003 \001(\rR\rtermi" +
      "nal-type\022 \n\013browse_tool\030\004 \001(\tR\013browse-to" +
      "olB\017\n\rcom.telemetryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gn_terminal_event_TerminalEvents_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gn_terminal_event_TerminalEvents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gn_terminal_event_TerminalEvents_descriptor,
        new java.lang.String[] { "TerminalEvent", });
    internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_descriptor =
      internal_static_gn_terminal_event_TerminalEvents_descriptor.getNestedTypes().get(0);
    internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gn_terminal_event_TerminalEvents_TerminalEvent_descriptor,
        new java.lang.String[] { "EventTime", "ClientMacAddress", "TerminalType", "BrowseTool", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
